import re
import re
from typing import Dict, Any


class TradutorOfflineUltraRapido:
	def __init__(self):
		self.padroes = {
		# ERROS PRINCIPAIS
		r'\bfile not found\b': 'arquivo não encontrado',
		r'\bimported but unused\b': 'importado mas não utilizado',

			# ESTADOS
		r'\berror\b': 'erro',
		r'\bfailed\b': 'falhou',
		r'\bsuccess(fully)?\b': 'sucesso',
		r'\bwarning\b': 'aviso',

		# STATUS
		r'\bstarted\b': 'iniciado',
		r'\bstopped\b': 'parado',

		# PREPOSIÇÕES E CONJUNÇÕES
		r'\bto\b': 'para',
		r'\bis\b': 'está',
		r'\bon\b': 'na',
		r'\bfor\b': 'para',
		r'\bof\b': 'de',
		r'\bfrom\b': 'do',
		r'\bwith\b': 'com',

		# TÉCNICO
		r'\bfile\b': 'arquivo',
		r'\bsystem\b': 'sistema',
		r'\bservice\b': 'serviço',
		r'\bport\b': 'porta',
		r'\bdatabase\b': 'banco de dados',
		r'\bconnection\b': 'conexão',
		r'\bnetwork\b': 'rede',
		r'\bprocess\b': 'processo',
		r'\bmodule\b': 'módulo',
		r'\buser\b': 'usuário',

		# ESPECÍFICOS DOS TESTES
		r'\btimed out\b': 'tempo esgotado',
		r'\bread-only\b': 'somente leitura',
		r'\brefused\b': 'recusado',
		r'\blow disk space\b': 'espaço em disco baixo',
		r'\ballocate memory\b': 'alocar memória',
		r'\bterminated\b': 'terminado',
		r'\bexpired\b': 'expirado',
		r'\bshared library\b': 'biblioteca compartilhada',
		r'\bunreachable\b': 'inalcançável',
		r'\bnot permitted\b': 'não permitido',
		r'\bcleared\b': 'limpo',
		r'\bloaded\b': 'carregado',
		r'\bresolve host\b': 'resolver hostname',
		# ESTADOS E RESULTADOS
		r'\bis not defined\b': 'não está definido',
		r'\berrors?\b': 'erros',
		r'\bwarnings?\b': 'avisos',
		r'\bfailed?\b': 'falhou',
		r'\bfailure\b': 'falha',
		r'\bsuccess(ful)?\b': 'sucesso',
		r'\bunknown\b': 'desconhecido',
		r'\binvalid\b': 'inválido',
		r'\bvalid\b': 'válido',
		r'\bmissing\b': 'ausente',
		r'\bfound\b': 'encontrado',
		r'\bnot found\b': 'não encontrado',
		r'\bempty\b': 'vazio',

		# STATUS
		r'\bloaded?\b': 'carregado',
		r'\bloading\b': 'carregando',
		r'\bunloaded\b': 'descarregado',
		r'\bstarted?\b': 'iniciado',
		r'\bstarting\b': 'iniciando',
		r'\bstopped?\b': 'parado',
		r'\bstopping\b': 'parando',
		r'\brunning\b': 'em execução',
		r'\bfinished\b': 'finalizado',
		r'\bcompleted\b': 'concluído',
		r'\baborted\b': 'abortado',
		r'\bcancelled\b': 'cancelado',

		# ACESSO E SEGURANÇA
		r'\bdenied?\b': 'negado',
		r'\brefused?\b': 'recusado',
		r'\bforbidden\b': 'proibido',
		r'\ballowed?\b': 'permitido',
		r'\bavailable\b': 'disponível',
		r'\bunavailable\b': 'indisponível',
		r'\bsupported?\b': 'suportado',
		r'\bunsupported\b': 'não suportado',
		r'\benabled?\b': 'ativado',
		r'\bdisabled?\b': 'desativado',

		# TEMPO E LIMITES
		r'\btimeout(s)?\b': 'tempo limite',
		r'\bexpired?\b': 'expirado',
		r'\bretry(ies)?\b': 'tentar novamente',
		r'\blimit\b': 'limite',
		r'\bexceeded?\b': 'excedido',

		# ARQUIVOS E DIRETÓRIOS
		r'\bfile(s)?\b': 'arquivo(s)',
		r'\bfolder(s)?\b': 'pasta(s)',
		r'\bdirectory(ies)?\b': 'diretório(ies)',
		r'\bpath(s)?\b': 'caminho(s)',
		r'\bname(s)?\b': 'nome(s)',
		r'\bextension\b': 'extensão',
		r'\bsize(s)?\b': 'tamanho(s)',
		r'\bmodified\b': 'modificado',
		r'\bcreated\b': 'criado',
		r'\bdeleted?\b': 'excluído',
		r'\bremove(d)?\b': 'remover/removido',
		r'\brename(d)?\b': 'renomear/renomeado',
		r'\bcopy(ied)?\b': 'copiar/copiado',
		r'\bmove(d)?\b': 'mover/movido',
		r'\bread\b': 'ler',
		r'\bwrite(n)?\b': 'escrever/escrito',
		r'\bexecute(able)?\b': 'executar/executável',
		r'\bappend\b': 'acrescentar',
		r'\bopen(ed)?\b': 'abrir/aberto',
		r'\bclose(d)?\b': 'fechar/fechado',
		r'\bsave(d)?\b': 'salvar/salvo',

		# PERMISSÕES
		r'\bpermission(s)?\b': 'permissão(ões)',
		r'\baccess\b': 'acesso',
		r'\bowner\b': 'dono',
		r'\bgroup\b': 'grupo',
		r'\bothers?\b': 'outros',
		r'\bread-only\b': 'somente leitura',
		r'\bread-write\b': 'leitura e escrita',
		r'\blocked?\b': 'bloqueado',
		r'\bunlocked\b': 'desbloqueado',

		# USUÁRIOS E AUTENTICAÇÃO
		r'\buser(s)?\b': 'usuário(s)',
		r'\broot\b': 'root',
		r'\badmin(istrator)?\b': 'admin/administrador',
		r'\bguest\b': 'convidado',
		r'\bsession(s)?\b': 'sessão(ões)',
		r'\blogin\b': 'login',
		r'\blogout\b': 'logout',
		r'\bauthenticated?\b': 'autenticado',
		r'\bpassword\b': 'senha',
		r'\busername\b': 'nome de usuário',

		# REDE E CONEXÃO
		r'\bconnection(s)?\b': 'conexão(ões)',
		r'\bconnected?\b': 'conectado',
		r'\bdisconnected?\b': 'desconectado',
		r'\boffline\b': 'offline',
		r'\bonline\b': 'online',
		r'\bhost(s)?\b': 'host(s)',
		r'\bserver(s)?\b': 'servidor(es)',
		r'\bclient(s)?\b': 'cliente(s)',
		r'\baddress(es)?\b': 'endereço(s)',
		r'\bip\b': 'ip',
		r'\bport(s)?\b': 'porta(s)',
		r'\bprotocol(s)?\b': 'protocolo(s)',
		r'\brequest(s)?\b': 'requisição(ões)',
		r'\bresponse(s)?\b': 'resposta(s)',

		# SISTEMA
		r'\bsystem\b': 'sistema',
		r'\bprocess(es)?\b': 'processo(s)',
		r'\bservice(s)?\b': 'serviço(s)',
		r'\bmemory\b': 'memória',
		r'\bdisk(s)?\b': 'disco(s)',
		# === SEU DICIONÁRIO ANTIGO (já convertido) ===
		r'\bis not defined\b': 'não está definido',
		r'\berrors?\b': 'erros',
		r'\bwarnings?\b': 'avisos',
		r'\bfailed?\b': 'falhou',
		r'\bsuccess(ful)?\b': 'sucesso',

		# === NOVAS PALAVRAS QUE VOCÊ ACABOU DE MANDAR ===
		r'\bdevice(s)?\b': 'dispositivo(s)',
		r'\bdriver(s)?\b': 'driver(s)',
		r'\bhardware\b': 'hardware',
		r'\bsoftware\b': 'software',
		r'\bresource(s)?\b': 'recurso(s)',
		r'\blimits?\b': 'limites',
		r'\barchitecture\b': 'arquitetura',
		r'\bplatform\b': 'plataforma',
		r'\benvironment\b': 'ambiente',
		r'\bvariable(s)?\b': 'variável(s)',
		r'\blocale\b': 'localidade',
		r'\bencoding\b': 'codificação',
		r'\bdecoding\b': 'decodificação',
		r'\bmodule(s)?\b': 'módulo(s)',
		r'\bpackage(s)?\b': 'pacote(s)',
		r'\blibrary(ies)?\b': 'biblioteca(s)',
		r'\bfunction(s)?\b': 'função(ões)',
		r'\bclass(es)?\b': 'classe(s)',
		r'\bargument(s)?\b': 'argumento(s)',
		r'\bparameter(s)?\b': 'parâmetro(s)',
		r'\breturns?\b': 'retornos',
		r'\bvalue(s)?\b': 'valor(es)',
		r'\btype(s)?\b': 'tipo(s)',
		r'\binstance(s)?\b': 'instância(s)',
		r'\bobject(s)?\b': 'objeto(s)',
		r'\battribute(s)?\b': 'atributo(s)',
		r'\bproperty(ies)?\b': 'propriedade(s)',
		r'\biterator\b': 'iterador',
		r'\biterable\b': 'iterável',
		r'\blist(s)?\b': 'lista(s)',
		r'\btuple(s)?\b': 'tupla(s)',
		r'\bdict(ionary)?\b': 'dicionário',
		r'\bset(s)?\b': 'conjunto(s)',
		r'\bbool(ean)?\b': 'booleano',
		r'\bint\b': 'inteiro',
		r'\bfloat\b': 'ponto flutuante',
		r'\bshould\b': 'deve',
		r'\bbe\b': 'ser',
		r'\bor\b': 'ou',
		r'\band\b': 'e',

		# GIT
		r'\bgit\b': 'git',
		r'\brepository(ies)?\b': 'repositório(s)',
		r'\bmerge\b': 'merge',
		r'\bpull\b': 'puxar',
		r'\bpush\b': 'enviar',
		r'\borigin\b': 'original',
		r'\bremote\b': 'remoto',
		r'\bstaged\b': 'preparado',
		r'\bconflict(s)?\b': 'conflito(s)',
		r'\bhistory\b': 'histórico',

		# DOCKER
		r'\bcontainer(s)?\b': 'contêiner(es)',
		r'\bimage(s)?\b': 'imagem(ens)',
		r'\bvolume(s)?\b': 'volume(s)',
		r'\bnetwork(s)?\b': 'rede(s)',
		r'\bcompose\b': 'compose',
		r'\btagged\b': 'tagueado',
		r'\bbuilt\b': 'construído',
		r'\brun\b': 'executar',
		r'\battach\b': 'anexar',
		r'\bdetach\b': 'desanexar',
		r'\binspect\b': 'inspecionar',

		# DATABASE
		r'\bdatabase(s)?\b': 'banco de dados',
		r'\btable(s)?\b': 'tabela(s)',
		r'\brow(s)?\b': 'linha(s)',
		r'\bcolumn(s)?\b': 'coluna(s)',
		r'\brecord(s)?\b': 'registro(s)',
		r'\bindex(es)?\b': 'índice(s)',
		r'\bquery(ies)?\b': 'consulta(s)',
		r'\btransaction(s)?\b': 'transação(ões)',
		r'\bschema(s)?\b': 'esquema(s)',

		# ERROS/CRASH
		r'\bcrash(ed)?\b': 'travamento/travou',
		r'\bhang(ed)?\b': 'congelar/congelado',
		r'\bfreeze(n)?\b': 'congelar/congelado',
		r'\bissue(s)?\b': 'problema(s)',
		r'\bfix(ed)?\b': 'corrigir/corrigido',
		r'\bpatched\b': 'corrigido',
		r'\bworkaround\b': 'solução alternativa',
		r'\bdebugging\b': 'depuração',
		r'\btrace(back)?\b': 'rastreamento',
		r'\bsource code\b': 'código-fonte',
		r'\bcompile(d)?\b': 'compilar/compilado',
		r'\bsyntax\b': 'sintaxe',
		r'\bparse(d)?\b': 'analisar/analisado',

		# === ANTERIORES (resumido) ===
		r'\berror(s)?\b': 'erro(s)',
		r'\bfailed?\b': 'falhou',
		r'\bsuccess\b': 'sucesso',
		r'\bfile(s)?\b': 'arquivo(s)',
		r'\bpermission denied\b': 'permissão negada',

		# === NOVAS TRADUÇÕES QUE VOCÊ MANDOU AGORA ===
		r'\bgrammar\b': 'gramática',
		r'\brule(s)?\b': 'regra(s)',
		r'\bloop(s)?\b': 'laço(s)',
		r'\bwhile\b': 'while',
		r'\bcase\b': 'caso',
		r'\bcontinue\b': 'continue',
		r'\basync\b': 'assíncrono',
		r'\bsync\b': 'síncrono',
		r'\btrue\b': 'verdadeiro',
		r'\bfalse\b': 'falso',
		r'\bnone\b': 'nenhum',
		r'\bnull\b': 'nulo',
		r'\bundefined\b': 'indefinido',
		r'\bdefault value\b': 'valor padrão',
		r'\boverflow\b': 'estouro',
		r'\bunderflow\b': 'subfluxo',
		r'\bdivide|division\b': 'dividir/divisão',
		r'\bzero\b': 'zero',
		r'\bnan\b': 'nan',
		r'\binfinity\b': 'infinito',
		r'\bpath separator\b': 'separador de caminho',
		r'\bnewline\b': 'quebra de linha',
		r'\bwhitespace\b': 'espaço em branco',
		r'\btab\b': 'tabulação',
		r'\bspace(s)?\b': 'espaço(s)',
		r'\bindent(ation)?\b': 'indentar/indentação',
		r'\bconfig(s)?|configuration(s)?\b': 'configuração(ões)',
		r'\bsubting(s)?\b': 'configurações',
		r'\boption file\b': 'arquivo de opções',
		r'\bconfig file\b': 'arquivo de configuração',
		r'\b\.env file\b': 'arquivo .env',
		r'\blogging\b': 'registro de logs',
		r'\blevel(s)?\b': 'nível(éis)',
		r'\bverbose(ity)?\b': 'verboso/verbosidade',
		r'\bqueue(s)?\b': 'fila(s)',
		r'\bstack\b': 'pilha',
		r'\bbuffer(s)?\b': 'buffer(s)',
		r'\bcache(d)?\b': 'cache/em cache',
		r'\bhit\b': 'acerto',
		r'\bmiss\b': 'falha',
		r'\bthread-safe\b': 'seguro para threads',
		r'\bunsafe\b': 'inseguro',
		r'\brace\b': 'condição de corrida',
		r'\bdeadlock\b': 'deadlock',
		r'\block(s)?\b': 'bloqueio(s)',
		r'\bmutex\b': 'mutex',
		r'\bsemaphore\b': 'semáforo',
		r'\bretry count\b': 'número de tentativas',
		r'\binterval\b': 'intervalo',
		r'\bdelay\b': 'atraso',
		r'\bschedule(d)?\b': 'agendar/agendado',
		r'\bjob(s)?|task(s)?\b': 'tarefa(s)',

		# CRIPTO/SEGURANÇA
		r'\bhost key\b': 'chave do host',
		r'\bpublic key\b': 'chave pública',
		r'\bprivate key\b': 'chave privada',
		r'\bfingerprint\b': 'impressão digital',
		r'\bcipher\b': 'cifra',
		r'\balgorithm(s)?\b': 'algoritmo(s)',
		r'\bsalt\b': 'sal',
		r'\biv\b': 'vetor de inicialização',

		# HTTP
		r'\bsession id\b': 'id de sessão',
		r'\brequest id\b': 'id de requisição',
		r'\btransaction id\b': 'id de transação',
		r'\btrace id\b': 'id de rastreamento',
		r'\bmethod(s)?\b': 'método(s)',
		r'\bdelete\b': 'delete',
		r'\bstatus code\b': 'código de status',
		r'\bheader(s)?\b': 'cabeçalho(s)',
		r'\bbody\b': 'corpo',
		r'\bcookie(s)?\b': 'cookie(s)',

		# SISTEMA/CLI
		r'\bcli\b': 'linha de comando',
		r'\bconsole\b': 'console',
		r'\bcommand(s)?\b': 'comando(s)',
		r'\bexit code|exit status\b': 'código/status de saída',
		r'\bdistribution\b': 'distribuição',
		r'\bkernel version\b': 'versão do kernel',
		r'\bshell script\b': 'script de shell',

		# GERENCIAMENTO
		r'\bservice manager\b': 'gerenciador de serviços',
		r'\bhostname|host name\b': 'hostname/nome do host',
		r'\buptime\b': 'tempo de atividade',
		r'\bdowntime\b': 'tempo de inatividade',
		r'\bhealth(y)?\b': 'saudável/não saudável',

		# COMANDOS
		r'\bstart\b': 'iniciar',
		r'\bstop\b': 'parar',
		r'\brestart(ed)?\b': 'reiniciar/reiniciado',
		r'\breload(ed)?\b': 'recarregar/recarregado',

		# PACOTES
		r'\bpackage manager\b': 'gerenciador de pacotes',
		r'\binstall(ed)?\b': 'instalar/instalado',
		r'\bupdate|upgrade\b': 'atualizar',

		# MEMORY
		r'\bmemory leak\b': 'vazamento de memória',
		r'\bgarbage collector\b': 'coletor de lixo',

		# DATABASE
		r'\bquery plan\b': 'plano de consulta',
		r'\breplica(tion)?\b': 'réplica/replicação',

		# SEGURANÇA
		r'\bsecurity\b': 'segurança',
		r'\bauthentication\b': 'autenticação',
		r'\bauthorization\b': 'autorização',

		# === ERROS COMUNS PYTHON/TERMINAL ===
		r'\berror(s)?\b': 'erro(s)',
		r'\bpermission denied\b': 'permissão negada',
		r'\baccess denied\b': 'acesso negado',
		r'\bcommand not found\b': 'comando não encontrado',
		r'\bno such file or directory\b': 'arquivo ou diretório inexistente',
		r'\bmodule not found\b': 'módulo não encontrado',
		r'\bfailed?\b': 'falhou',
		r'\bsuccess(ful)?\b': 'sucesso',
		r'\bwarning(s)?\b': 'aviso(s)',

		# === SUAS ÚLTIMAS TRADUÇÕES ===
		r'\bprimary\b': 'primário',
		r'\bsecondary\b': 'secundário',
		r'\bleader election\b': 'eleição de líder',
		r'\bconsensus\b': 'consenso',
		r'\bobject storage\b': 'armazenamento de objetos',
		r'\bfilesystem\b': 'sistema de arquivos',
		r'\bpagination\b': 'paginação',
		r'\boffset pagination\b': 'paginação por deslocamento',
		r'\bcursor pagination\b': 'paginação por cursor',
		r'\bthrottling\b': 'restrição de taxa',
		r'\brate limit\b': 'limite de taxa',
		r'\bcache (?:key|entry)\b': 'chave/entrada de cache',
		r'\bcache size\b': 'tamanho do cache',
		r'\bversioning\b': 'versionamento',
		r'\bschema validation\b': 'validação de esquema',
		r'\bvalidator\b': 'validador',
		r'\bvalidation\b': 'validação',
		r'\bserializer\b': 'serializador',
		r'\bdeserializer\b': 'desserializador',
		r'\bmiddleware stack\b': 'pilha de middleware',
		r'\b(?:job|task) id\b': 'id da tarefa',
		r'\bcron job\b': 'tarefa cron',
		r'\bschedule expression\b': 'expressão de agendamento',
		r'\bkernel panic\b': 'pânico do kernel',
		r'\bpanic\b': 'pânico',
		r'\bnamespace isolation\b': 'isolamento de namespace',
		r'\bhealthcheck\b': 'verificação de saúde',
		r'\bbind mount\b': 'montagem vinculada',
		r'\b(?:image|container) id\b': 'id da imagem/contêiner',
		r'\blayer(s)?\b': 'camada(s)',
		r'\b(?:bridge|overlay) network\b': 'rede bridge/overlay',

		# === GIT AVANÇADO ===
		r'\bgit hook\b': 'gancho do git',
		r'\b(?:pre-commit|pre-push|post-merge)\b': 'pre-commit/pre-push/post-merge',
		r'\b(?:remote|origin) url\b': 'url remota/origin',
		r'\b(?:upstream|tag|branch) name\b': 'nome upstream/tag/branch',

		# === PYTHON/DEVOPS ===
		r'\b(?:venv path|site-packages)\b': 'caminho do venv/site-packages',
		r'\b(?:requirements|lock) file\b': 'arquivo de requisitos/bloqueio',
		r'\b(?:unit|integration) test\b': 'teste unitário/integração',
		r'\btest (?:suite|runner)\b': 'suíte/executor de testes',

		# === SEGURANÇA ===
		r'\bsqli\b': 'injeção sql',
		r'\bopen redirect\b': 'redirecionamento aberto',
		r'\b(?:ip whitelist|ip blacklist)\b': 'lista branca/negra de ip',
		r'\b(?:allowlist|denylist)\b': 'lista de permitidos/negados',

		# === SISTEMA/CONTAINERS ===
		r'\bload balancer\b': 'balanceador de carga',
		r'\b(?:circuit breaker|bulkhead)\b': 'disjuntor/compartimento',
		r'\bdeployment\b': 'implantação',
		r'\b(?:canary|rolling update)\b': 'canário/atualização gradual',

		# === MÉTRICAS/OBSERVABILIDADE ===
		r'\b(?:metric|observability|telemetry)\b': 'métrica/observabilidade/telemetria',
		r'\b(?:counter|gauge|histogram)\b': 'contador/medidor/histograma',

		# === ERROS PIP/NPM/COMUNS ===
		r'\bunknown command\b': 'comando desconhecido',
		r'\bmaybe you meant\b': 'talvez você quis dizer',
		r'\bsuccessfully installed\b': 'instalado com sucesso',
		r'\brequirement already satisfied\b': 'dependência já satisfeita',
		r'\binstalling?\b': 'instalando',
		r'\b(?:un)?installing?\b': 'desinstalando/instalando',

		# === ERROS PYTHON ESPECÍFICOS ===
		r'\b(?:Syntax|Indentation|Name|Import)Error\b': 'erro de sintaxe/indentação/nome/importação',
		r'\bModuleNotFoundError\b': 'módulo não encontrado',
		r'\b(?:connection|operation) (?:timed out|refused)\b': 'conexão/operação expirada/recusada',

		# === ERROS SISTEMA ===
		r'\b(?:disk full|no space left)\b': 'disco cheio/sem espaço',
		r'\bread-only file system\b': 'sistema de arquivos somente leitura',
		r'\b(?:out of|insufficient) memory\b': 'memória insuficiente',

		# === GIT/REPO ===
		r'\bworking (?:tree|directory)\b': 'árvore/diretório de trabalho',
		r'\bclean|detached\b': 'limpo/destacado',

		# === PALAVRAS SOLTAS ===
		r'\b(?:reset|error|not|temporarily|internal|bad|timed|already)\b': 'redefinida/erro/não/temporariamente/interno/inválida/expirou/já',
		r'\b(?:exists|busy|only|cannot|broken|corrupted|too|large|long)\b': 'existe/ocupado/somente/não foi possível/quebrada/corrompido/muito/grande/longo',
		r'\battribute error\b': 'erro de atributo',
		r'\bkey error\b': 'erro de chave',
		r'\btype error\b': 'erro de tipo',
		r'\bvalue error\b': 'erro de valor',
		r'\bindex error\b': 'erro de índice',
		r'\bstop iteration\b': 'parar iteração',
		r'\bassertion error\b': 'erro de afirmação',
		r'\bunbound local\b': 'local não vinculado',
		r'\bunhashable type\b': 'tipo não hashável',
		r'\bobject has no attribute\b': 'objeto não tem atributo',
		r'\blist index out of range\b': 'índice de lista fora do intervalo',
		r'\bdict key error\b': 'erro de chave do dicionário',
		r'\b(?:str|int|float|tuple|set|bytes|function|method|class|generator) (?:object is not (?:callable|subscriptable)|has no attribute)\b': 'objeto não é chamável/indexável/não tem atributo',
		r'\b(?:context manager|with statement)\b': 'gerenciador de contexto/instrução with',
		r'\bfinally block\b': 'bloco finally',
		r'\b(?:try except|raise exception|catch exception|handle error)\b': 'tentar exceto/levantar exceção/capturar exceção/tratar erro',

		# === ERROS SINTAXE ===
		r'\b(?:syntax|tab|invalid syntax|invalid character|eol while scanning|unclosed|unterminated|unexpected (?:eof|indent))\b': 'erro de sintaxe/tabulação/sintaxe inválida/caractere inválido/fim de linha/string não fechada/indentação inesperada',

		# === IMPORTAÇÃO ===
		r'\b(?:import error|cannot import|module not found|circular import)\b': 'erro de importação/não foi possível importar/módulo não encontrado/importação circular',

		# === ERROS SISTEMA/IO ===
		r'\bunexpected\b': 'inesperado',

		r'\b(?:operation|file|directory|path) (?:not found|not permitted|invalid)\b': 'operação/arquivo/diretório/caminho inválido/não encontrado/não permitido',
		r'\b(?:no space left|disk quota exceeded|disk full)\b': 'sem espaço/cota excedida/disco cheio',
		r'\bread only file system\b': 'sistema de arquivos somente leitura',

		# === REDE ===
		r'\b(?:connection|operation|host|network) (?:timed out|refused|reset|aborted|unreachable)\b': 'conexão/operação/host/rede expirada/recusada/resetada/abortada/inacessível',
		r'\b(?:broken pipe|no route to host)\b': 'pipe quebrado/sem rota para host',

		# === ARQUIVOS/PACOTES ===
		r'\b(?:requirements|__init__|setup)\.py\b': 'requirements/init/setup py',
		r'\b(?:pip|wheel|egg|lockfile)\b': 'pip/wheel/egg/arquivo de bloqueio',

		# === GERAL ===
		r'\b(?:traceback|exception)\b': 'rastreamento de erro/exceção',
		r'\bsuccessfully?\b': 'com sucesso',
		r'\bfailed?\b': 'falhou',

			# === SOCKET/NETWORK ERROS ===
			r'\bsocket is (?:already|not) connected\b': 'socket já/não conectado',
			r'\bcannot send after socket shutdown\b': 'não foi possível enviar após shutdown do socket',
			r'\b(?:operation on closed socket|fd is not socket)\b': 'operação em socket fechado/fd não é socket',
			r'\bsocket too large\b': 'socket muito grande',
			r'\b(?:wrong protocol|protocol option not supported)\b': 'tipo/ opção de protocolo não suportada',
			r'\b(?:address|network interface) (?:not available|is not configured)\b': 'endereço/interface não disponível/configurada',

			# === ERROS PYTHON (camelCase + snake_case) ===
			r'\b(?:attribute|key|type|value|index)error\b': 'erro de atributo/chave/tipo/valor/índice',
			r'\bstopiteration\b': 'parar iteração',
			r'\bassertionerror\b': 'erro de afirmação',
			r'\bunboundlocalerror\b': 'local não vinculado',
			r'\bunhashabletype\b': 'não hashável',
			r'\blistindexoutofrange\b': 'índice fora intervalo',
			r'\b(?:str|int|float|tuple|set|bytes|module|function|method|class|generator)(?:notcallable|notsubscriptable|noattribute)\b': 'objeto não chamável/indexável/sem atributo',

			# === CONTROLE DE EXCEÇÃO ===
			r'\b(?:contextmanager|withstatement|finallyblock|tryexcept|raiseexception|catchexception|handleerror)\b': 'gerenciador contexto/instrução with/bloco finally/tentar exceto/levantar exceção/capturar exceção/tratar erro',

			# === SINTAXE ===
			r'\b(?:syntaxerror|taborerror|unexpected(?:eof|indent)|mixedtabspaces|invalid(?:character|escapes?))\b': 'erro de sintaxe/tabulação/indentação/caractere inválido/escape inválido',
			r'\b(?:unclosed|unterminated|string|parenthesis)\b': 'string/parêntese não fechada/terminada',

			# === IMPORTAÇÃO ===
			r'\b(?:importerror|cannotimport|modulenotfound|circularimport)\b': 'erro de importação/não foi possível importar/módulo não encontrado/import circular',

			# === ARQUIVOS/SISTEMA ===
			r'\b(?:permissiondenied|operationnotpermitted|nosuch(?:device|file)|notadirectory|isadirectory|invalidargument)\b': 'permissão negada/operação não permitida/dispositivo/arquivo inexistente/não é diretório/é diretório/argumento inválido',
			r'\b(?:nospaceleft|diskquotaexceeded|readonlyfilesystem)\b': 'sem espaço/cota excedida/somente leitura',

			# === REDE COMPLETA ===
			r'\b(?:connection|operation|host|network)(?:reset|aborted|refused|timedout|unreachable)\b': 'conexão/operação/host/rede resetada/abortada/recusada/expirada/inacessível',
			r'\b(?:brokenpipe|networkdown|no route to host)\b': 'pipe quebrado/rede inativa/sem rota',

			# === PACOTES PYTHON ===
			r'\b(?:setuppy|pyprojecttoml|requirements\.txt|initpy|wheelfile|eggfile)\b': 'setup py/pyproject toml/requirements txt/init py/arquivo wheel/egg',

			# === ARQUIVO/SISTEMA ===
			r'\b(?:filetoolarge|pathtoolong|toomanyopenfiles|filetableoverflow)\b': 'arquivo/caminho muito longo/muitos arquivos abertos/overflow tabela',

					# === SOCKET/NETWORK (suas últimas) ===
					r'\bnodataavailable\b': 'sem dados',
					r'\bdevicetimeout\b': 'timeout dispositivo',
					r'\boutofmemory\b': 'sem memória',
					r'\b(?:operationwouldblock|socket(?:alreadyconnected|notconnected|toolarge))\b': 'operação bloquearia/socket conectado/desconectado/gigante',
					r'\b(?:fdnotsocket|fdnotopenfile)\b': 'fd não socket/aberto',
					r'\bdestinationportunreachable\b': 'porta fora',
					r'\bnobufferspace\b': 'buffer lotado',
					r'\b(?:noroutetohost|transportendpoint)\b': 'sem rota host/transporte final',

					# === ERROS PYTHON COMPACTOS ===
					r'\b(?:attribute|key|type|value|index)error\b': 'erro de atributo/chave/tipo/valor/índice',
					r'\b(?:stopiteration|assertionerror|unboundlocalerror)\b': 'parar iteração/erro afirmação/local não vinculado',

					# === SISTEMA LINUX/DEBUG ===
					r'\b(?:segfault|buserror|stackoverflow|bufferoverflow)\b': 'falha memória/erro barramento/pilha esgotada/transbordamento buffer',
					r'\b(?:memoryleak|heapcorruption|doublefree|useafterfree)\b': 'vazamento memória/montículo corrompido/dupla liberação/uso pós liberação',

					# === ARQUITETURAS ===
					r'\b(?:powerpc|riscv|aarch64|s390x|ppc64le|loongarch|hexagon)\b': 'powerpc/riscv/aarch64/s390x/ppc64le/loongarch/hexagon arquitetura',

					# === RUNTIMES/JS ===
					r'\b(?:llvm|clang|quickjs|spidermonkey|d8|wasmer|wasmtime|wasm3)\b': 'llvm/clang/quickjs/spidermonkey/d8/wasmer/wasmtime/wasm3',

					# === FILESYSTEMS ===
					r'\b(?:btrfs|zfs|xfs|ext4?|jfs|reiserfs|ntfs|vfat|exfat|overlayfs|tmpfs)\b': 'btrfs/zfs/xfs/ext4/jfs/reiserfs/ntfs/vfat/exfat/overlayfs/tmpfs',

					# === DEBUG TOOLS ===
					r'\b(?:gdb|lldb|strace|ltrace|perf|valgrind|addresssanitizer|threadsanitizer)\b': 'gdb/lldb/strace/ltrace/perf/valgrind/asan/tsan debug',

					# === CONTAINERS/SEGURANÇA ===
					r'\b(?:systemd|dbus|cgroups?|seccomp|apparmor|selinux)\b': 'systemd/dbus/cgroups/seccomp/apparmor/selinux',

					# === KERNEL/MONITORING ===
					r'\b(?:epoll|kqueue|inotify|bpftrace|ebpf|sysdig)\b': 'epoll/kqueue/inotify/bpftrace/ebpf/sysdig',

					# === ERROS COMUNS ===
					r'\b(?:permissiondenied|connection(?:refused|timedout)|notsupported)\b': 'permissão negada/conexão recusada/expirou/não suportado',
					# === KERNEL LINUX - TRABALHO/TIMER ===
					r'\bwork_struct\b': 'estrutura trabalho',
					r'\bdelayed_work\b': 'trabalho atrasado',
					r'\btimer_list\b': 'lista timers',
					r'\bhrtimer\b': 'timer alta resolução',

					# === SYNCHRONIZATION ===
					r'\bfutex\b': 'futex primitiva',
					r'\b(?:spin|mutex|rw|semaphore|rwsem)(?:_lock|_unlock|_down|_up)?\b': 'spinlock/mutex/rw/semáforo bloqueio/liberar',
					r'\b(?:wake_up|try_to_wake_up)\b': 'acordar/tentar acordar',
					r'\bschedule_timeout\b': 'agendar timeout',

					# === CONTEXT ===
					r'\b(?:context_switch|irq|preempt)(?:_disable|_enable|_context)?\b': 'troca contexto/irq/preempt desabilitar/habilitar/contexto',

					# === LOCKS ===
					r'\b(?:lockdep|lock_(?:chain|class|validator))\b': 'lockdep/verificador/cadeia/classe bloqueios',

					# === RCU ===
					r'\brcu_(?:read_(?:lock|unlock)|synchronize|barrier)\b': 'rcu leitura/liberar/sincronizar/barreira',

					# === MEMORY MANAGEMENT ===
					r'\b(?:page|slab|kmalloc|vmalloc|kswapd|oom)\b': 'página/slab/kmalloc/vmalloc/kswapd/oom',
					r'\b(?:gfp_(?:kernel|atomic|user|dma|highmem))\b': 'kernel/atômica/usuário/dma/alta memória alocação',
			r"'import'\s*\(<unknown>,\s*line\s*\d+\)": "erro de sintaxe na palavra-chave import",

			# === ERROS GERAIS ===
					r'\b(?:permission denied|connection refused|not found)\b': 'permissão negada/conexão recusada/não encontrado',
					r'\bexpected one or more names after\b': 'esperado um ou mais nomes após',
					# === PYTHON ===
					r'\b(?:attribute|type|value)error\b': 'erro de atributo/tipo/valor',
		}
		self.padroes = {re.compile(k, re.IGNORECASE): v for k, v in self.padroes.items()}

	def traduzir(self, texto: Any) -> str:
		texto = str(texto).replace('_', ' ').replace('-', ' ')
		resultado = texto
		for padrao, traducao in self.padroes.items():
			resultado = padrao.sub(traducao, resultado)
		return resultado.capitalize()


# TESTE:
tradutor = TradutorOfflineUltraRapido()

def traduzir_saida(saida) -> str:
	return tradutor.traduzir(saida)


def traduzir_saida_(saida) -> str:
	saida = str(saida).replace('_',' ').replace('-',' ')
	if not isinstance(saida, str):
		if hasattr(saida, 'strerror'):
			saida = saida.strerror or str(saida)
		elif hasattr(saida, 'msg'):
			saida = saida.msg or str(saida)
		else:
			saida = str(saida)

	saida_original = saida
	saida_lower = saida.lower()

	for en, pt in TRANSLATE_MAP().items():
		pattern = r'\b' + re.escape(en.lower()) + r'\b'
		saida_lower = re.sub(pattern, pt.lower(), saida_lower)

	if saida_original.isupper():
		return saida_lower.upper()
	elif saida_original.istitle():
		return saida_lower.title()

	return str(saida_lower).capitalize()



def TRANSLATE_MAP():
	# Exemplo de dicionário
	return {
	"is not defined":"não está definido!",
	"errors": "erros",
	"warnings": "avisos",
	"failed": "falhou",
	"failure": "falha",
	"success": "sucesso",
	"successful": "bem-sucedido",
	"unknown": "desconhecido",
	"invalid": "inválido",
	"valid": "válido",
	"missing": "ausente",
	"found": "encontrado",
	"not found": "não encontrado",
	"empty": "vazio",
	"loaded": "carregado",
	"loading": "carregando",
	"unloaded": "descarregado",
	"started": "iniciado",
	"starting": "iniciando",
	"stopped": "parado",
	"stopping": "parando",
	"running": "em execução",
	"finished": "finalizado",
	"completed": "concluído",
	"aborted": "abortado",
	"cancelled": "cancelado",
	"denied": "negado",
	"refused": "recusado",
	"forbidden": "proibido",
	"allowed": "permitido",
	"available": "disponível",
	"unavailable": "indisponível",
	"supported": "suportado",
	"unsupported": "não suportado",
	"enabled": "ativado",
	"disabled": "desativado",
	"timeout": "tempo limite",
	"expired": "expirado",
	"retry": "tentar novamente",
	"retries": "tentativas",
	"limit": "limite",
	"exceeded": "excedido",
	"overridden": "sobrescrito",
	"default": "padrão",
	"custom": "personalizado",

	"file": "arquivo",
	"files": "arquivos",
	"folder": "pasta",
	"folders": "pastas",
	"directory": "diretório",
	"directories": "diretórios",
	"path": "caminho",
	"paths": "caminhos",
	"name": "nome",
	"names": "nomes",
	"extension": "extensão",
	"size": "tamanho",
	"sizes": "tamanhos",
	"modified": "modificado",
	"created": "criado",
	"deleted": "excluído",
	"remove": "remover",
	"removed": "removido",
	"rename": "renomear",
	"renamed": "renomeado",
	"copy": "copiar",
	"copied": "copiado",
	"move": "mover",
	"moved": "movido",
	"read": "ler",
	"write": "escrever",
	"written": "escrito",
	"execute": "executar",
	"executable": "executável",
	"append": "acrescentar",
	"open": "abrir",
	"opened": "aberto",
	"close": "fechar",
	"closed": "fechado",
	"save": "salvar",
	"saved": "salvo",
	"symlink": "link simbólico",
	"hardlink": "link físico",

	"permission": "permissão",
	"permissions": "permissões",
	"access": "acesso",
	"owner": "dono",
	"group": "grupo",
	"others": "outros",
	"read-only": "somente leitura",
	"read-write": "leitura e escrita",
	"locked": "bloqueado",
	"unlocked": "desbloqueado",
	"restricted": "restrito",
	"privileged": "com privilégios",
	"unprivileged": "sem privilégios",
	"admin": "admin",
	"administrator": "administrador",
	"root": "root",
	"user": "usuário",
	"users": "usuários",
	"guest": "convidado",
	"session": "sessão",
	"sessions": "sessões",
	"login": "login",
	"logout": "logout",
	"authenticated": "autenticado",
	"unauthenticated": "não autenticado",
	"authorized": "autorizado",
	"unauthorized": "não autorizado",
	"password": "senha",
	"username": "nome de usuário",
	"credentials": "credenciais",
	"key": "chave",
	"keys": "chaves",
	"certificate": "certificado",
	"certificates": "certificados",
	"signature": "assinatura",

	"connection": "conexão",
	"connections": "conexões",
	"connected": "conectado",
	"disconnected": "desconectado",
	"offline": "offline",
	"online": "online",
	"host": "host",
	"hosts": "hosts",
	"server": "servidor",
	"servers": "servidores",
	"client": "cliente",
	"clients": "clientes",
	"address": "endereço",
	"addresses": "endereços",
	"ip": "ip",
	"port": "porta",
	"ports": "portas",
	"protocol": "protocolo",
	"protocols": "protocolos",
	"request": "requisição",
	"requests": "requisições",
	"response": "resposta",
	"responses": "respostas",
	"status": "status",
	"latency": "latência",
	"bandwidth": "largura de banda",
	"throughput": "taxa de transferência",
	"packet": "pacote",
	"packets": "pacotes",
	"router": "roteador",
	"domain": "domínio",
	"timeouted": "expirado",
	"retrying": "re-tentando",

	"system": "sistema",
	"process": "processo",
	"processes": "processos",
	"service": "serviço",
	"services": "serviços",
	"signal": "sinal",
	"signals": "sinais",
	"memory": "memória",
	"disk": "disco",
	"disks": "discos",
	"volumes": "volumes",
	"partition": "partição",
	"partitions": "partições",
	"device": "dispositivo",
	"devices": "dispositivos",
	"driver": "driver",
	"drivers": "drivers",
	"hardware": "hardware",
	"software": "software",
	"resource": "recurso",
	"resources": "recursos",
	"limits": "limites",
	"architecture": "arquitetura",
	"platform": "plataforma",
	"environment": "ambiente",
	"variable": "variável",
	"variables": "variáveis",
	"locale": "localidade",
	"encoding": "codificação",
	"decoding": "decodificação",
	"module": "módulo",
	"modules": "módulos",
	"package": "pacote",
	"packages": "pacotes",
	"library": "biblioteca",
	"libraries": "bibliotecas",
	"function": "função",
	"functions": "funções",
	"class": "classe",
	"classes": "classes",
	"argument": "argumento",
	"arguments": "argumentos",
	"parameter": "parâmetro",
	"parameters": "parâmetros",
	"returns": "retornos",
	"value": "valor",
	"values": "valores",
	"type": "tipo",
	"types": "tipos",
	"instance": "instância",
	"instances": "instâncias",
	"object": "objeto",
	"objects": "objetos",
	"attribute": "atributo",
	"attributes": "atributos",
	"property": "propriedade",
	"properties": "propriedades",
	"iterator": "iterador",
	"iterable": "iterável",
	"list": "lista",
	"lists": "listas",
	"tuple": "tupla",
	"tuples": "tuplas",
	"dict": "dicionário",
	"dictionary": "dicionário",
	"set": "conjunto",
	"sets": "conjuntos",
	"bool": "booleano",
	"boolean": "booleano",
	"int": "inteiro",
	"should" : "deve",
	"be" : "ser",
	"float": "ponto flutuante",
	"or":'ou',
	"and":'e',
	"git": "git",
	"repository": "repositório",
	"repositories": "repositórios",
	"merge": "mergem",
		"pull": "puxar",
		"push": "enviar",
	"origin": "original",
	"remote": "remoto",
	"staged": "preparado",
	"conflict": "conflito",
	"conflicts": "conflitos",
	"history": "histórico",
	"container": "contêiner",
	"containers": "contêineres",
	"image": "imagem",
	"images": "imagens",
	"volume": "volume",
	"network": "rede",
	"compose": "compose",
	"tagged": "tagueado",
	"built": "construído",
	"run": "executar",
	"attach": "anexar",
	"detach": "desanexar",
	"inspect": "inspecionar",
	"database": "banco de dados",
	"databases": "bancos de dados",
	"table": "tabela",
	"tables": "tabelas",
	"row": "linha",
	"rows": "linhas",
	"columns": "colunas",
	"record": "registro",
	"records": "registros",
	"index": "índice",
	"indexes": "índices",
	"query": "consulta",
	"queries": "consultas",
	"transaction": "transação",
	"transactions": "transações",
	"schema": "esquema",
	"schemas": "esquemas",
	"constraint": "restrição",
	"constraints": "restrições",
	"connection pool": "pool de conexões",
		"crash": "travamento",
		"crashed": "travou",
		"hang": "congelar",
		"hanged": "congelado",
		"freeze": "congelar",
		"frozen": "congelado",
		"issue": "problema",
		"issues": "problemas",
		"problem": "problema",
		"problems": "problemas",
		"fix": "corrigir",
		"fixed": "corrigido",
		"patched": "corrigido",
		"workaround": "solução alternativa",
		"debugging": "depuração",
		"trace": "rastro",
		"traceback": "rastreamento",
		"frame": "quadro",
		"frames": "quadros",
		"line": "linha",
		"lines": "linhas",
		"column": "coluna",
		"offset": "deslocamento",
		"source": "fonte",
		"source code": "código-fonte",
		"compile": "compilar",
		"compiled": "compilado",
		"compiler": "compilador",
		"interpreted": "interpretado",
		"interpreter": "interpretador",
		"runtime": "tempo de execução",
		"build": "compilação",
		"optimize": "otimizar",
		"optimized": "otimizado",
		"optimization": "otimização",
		"option": "opção",
		"options": "opções",
		"argument list": "lista de argumentos",
		"syntax": "sintaxe",
		"semantic": "semântica",
		"semantics": "semântica",
		"parse": "analisar",
		"parsed": "analisado",
		"grammar": "gramática",
		"rule": "regra",
		"rules": "regras",
		"loop": "laço",
		"loops": "laços",
		"while": "while",
		"case": "caso",
		"continue": "continue",
		"async": "assíncrono",
		"sync": "síncrono",
		"true": "verdadeiro",
		"false": "falso",
		"none": "nenhum",
		"null": "nulo",
		"undefined": "indefinido",
		"default value": "valor padrão",
		"overflow": "estouro",
		"underflow": "subfluxo",
		"divide": "dividir",
		"division": "divisão",
		"zero": "zero",
		"nan": "nan",
		"infinity": "infinito",
		"path separator": "separador de caminho",
		"newline": "quebra de linha",
		"whitespace": "espaço em branco",
		"tab": "tabulação",
		"space": "espaço",
		"spaces": "espaços",
		"indent": "indentar",
		"indentation": "indentação",
		"unindent": "desindentar",
		"config": "configuração",
		"configs": "configurações",
		"configuration": "configuração",
		"settings": "configurações",
		"option file": "arquivo de opções",
		"config file": "arquivo de configuração",
		"env": "ambiente",
		".env file": "arquivo .env",
		"logging": "registro de logs",
		"level": "nível",
		"levels": "níveis",
		"verbose": "verboso",
		"verbosity": "verbosidade",
		"trace level": "nível de rastreamento",
		"debug level": "nível de depuração",
		"error level": "nível de erro",
		"queue": "fila",
		"queues": "filas",
		"stack": "pilha",
		"buffer": "buffer",
		"buffers": "buffers",
		"cache": "cache",
		"cached": "em cache",
		"hit": "acerto",
		"miss": "falha",
		"thread-safe": "seguro para threads",
		"unsafe": "inseguro",
		"race": "condição de corrida",
		"deadlock": "deadlock",
		"lock": "bloqueio",
		"locks": "bloqueios",
		"mutex": "mutex",
		"semaphore": "semáforo",
		"timeout value": "valor de tempo limite",
		"retry count": "número de tentativas",
		"interval": "intervalo",
		"delay": "atraso",
		"schedule": "agendar",
		"scheduled": "agendado",
		"job": "tarefa",
		"jobs": "tarefas",
		"task": "tarefa",
		"tasks": "tarefas",
		"host key": "chave do host",
		"public key": "chave pública",
		"private key": "chave privada",
		"fingerprint": "impressão digital",
		"cipher": "cifra",
		"algorithm": "algoritmo",
		"algorithms": "algoritmos",
		"hashed": "com hash",
		"salt": "sal",
		"iv": "vetor de inicialização",
		"session id": "id de sessão",
		"request id": "id de requisição",
		"transaction id": "id de transação",
		"trace id": "id de rastreamento",
		"method": "método",
		"methods": "métodos",
		"delete": "delete",
		"options method": "método options",
		"status code": "código de status",
		"headers": "cabeçalhos",
		"header": "cabeçalho",
		"body": "corpo",
		"payload": "payload",
		"cookie": "cookie",
		"cookies": "cookies",
		"session cookie": "cookie de sessão",
		"binary": "binário",
		"text": "texto",
		"format": "formato",
		"compressed": "comprimido",
		"uncompressed": "descomprimido",
		"archive": "arquivo compactado",
		"cli": "linha de comando",
		"console": "console",
		"command": "comando",
		"commands": "comandos",
		"script file": "arquivo de script",
		"piped": "encadeado",
		"exit code": "código de saída",
		"exit status": "status de saída",
		"distribution": "distribuição",
		"kernel version": "versão do kernel",
		"shell script": "script de shell",
		"batch file": "arquivo em lote",
		"service manager": "gerenciador de serviços",
		"host name": "nome do host",
		"hostname": "hostname",
		"fqdn": "nome de domínio completo",
		"subdomain": "subdomínio",
		"top-level domain": "domínio de topo",
		"master": "mestre",
		"worker node": "nó de trabalho",
		"leader": "líder",
		"follower": "seguidor",
		"queue length": "tamanho da fila",
		"load": "carga",
		"uptime": "tempo de atividade",
		"downtime": "tempo de inatividade",
		"health check": "verificação de saúde",
		"healthy": "saudável",
		"unhealthy": "não saudável",
		"role": "papel",
		"roles": "papéis",
		"policy": "política",
		"policies": "políticas",
		"scope": "escopo",
		"scopes": "escopos",
		"snapshot": "snapshot",
		"backup": "backup",
		"restore": "restaurar",
		"restored": "restaurado",
		"metrics": "métricas",
		"monitoring": "monitoramento",
		"alert": "alerta",
		"alerts": "alertas",
		"threshold": "limite",
		"thresholds": "limites",
		"schema migration": "migração de esquema",
		"migration": "migração",
		"migrations": "migrações",
		"seed": "seed",
		"seeding": "semeando",
		"orphan": "órfão",
		"stale": "obsoleto",
		"deprecated": "obsoleto",
		"legacy": "legado",
		"modern": "moderno",
		"hook": "gancho",
		"hooks": "ganchos",
		"queue worker": "worker de fila",
		"job queue": "fila de tarefas",
		"background": "plano de fundo",
		"foreground": "primeiro plano",
		"interactive": "interativo",
		"non-interactive": "não interativo",
		"batch": "lote",
		"no module" : "não tem modulo",
		"named"  : "chamado",
		"start": "iniciar",
		"stop": "parar",
		"restart": "reiniciar",
		"reload": "recarregar",
		"restarted": "reiniciado",
		"reloaded": "recarregado",
		"alias": "apelido",
		"shortcut": "atalho",
		"orphaned process": "processo órfão",
		"zombie process": "processo zumbi",
		"priority": "prioridade",
		"priorities": "prioridades",
		"min": "mínimo",
		"max": "máximo",
		"average": "média",
		"median": "mediana",
		"sample": "amostra",
		"samples": "amostras",
		"retry policy": "política de novas tentativas",
		"package manager": "gerenciador de pacotes",
		"install": "instalar",
		"installed": "instalado",
		"uninstall": "desinstalar",
		"uninstalled": "desinstalado",
		"update": "atualizar",
		"upgrade": "atualizar",
		"downgrade": "reverter versão",
		"allocator": "alocador",
		"allocation": "alocação",
		"allocated": "alocado",
		"deallocated": "desalocado",
		"leak": "vazamento",
		"memory leak": "vazamento de memória",
		"profile": "perfil",
		"profiling": "perfilamento",
		"sampler": "amostrador",
		"event": "evento",
		"events": "eventos",
		"listener": "ouvinte",
		"listeners": "ouvintes",
		"subscriber": "assinante",
		"publish": "publicar",
		"publisher": "publicador",
		"subscribe": "assinar",
		"unsubscribe": "cancelar assinatura",
		"queue name": "nome da fila",
		"topic": "tópico",
		"topics": "tópicos",
		"retry delay": "atraso entre tentativas",
		"backoff": "retrocesso",
		"exponential backoff": "retrocesso exponencial",
		"subnet": "sub-rede",
		"subnet mask": "máscara de sub-rede",
		"mac address": "endereço mac",
		"stdin redirection": "redirecionamento de stdin",
		"stdout redirection": "redirecionamento de stdout",
		"stderr redirection": "redirecionamento de stderr",
		"here document": "here document",
		"orphaned resource": "recurso órfão",
		"cleanup": "limpeza",
		"garbage collector": "coletor de lixo",
		"finalizer": "finalizador",
		"scope leak": "vazamento de escopo",
		"bootstrapper": "inicializador",
		"initializer": "inicializador",
		"lifecycle": "ciclo de vida",
		"startup": "inicialização",
		"shutdown": "desligamento",
		"security": "segurança",
		"vulnerability": "vulnerabilidade",
		"vulnerabilities": "vulnerabilidades",
		"attack": "ataque",
		"attacker": "atacante",
		"defender": "defensor",
		"authorization": "autorização",
		"authentication": "autenticação",
		"confidentiality": "confidencialidade",
		"integrity": "integridade",
		"availability": "disponibilidade",
		"audit": "auditoria",
		"auditing": "auditoria",
		"compliance": "conformidade",
		"access control list": "lista de controle de acesso",
		"query plan": "plano de consulta",
		"optimizer": "otimizador",
		"index scan": "varredura de índice",
		"table scan": "varredura de tabela",
		"lock wait": "espera de bloqueio",
		"hot standby": "standby quente",
		"replica": "réplica",
		"replication": "replicação",
		"primary": "primário",
		"secondary": "secundário",
		"leader election": "eleição de líder",
		"consensus": "consenso",
		"object storage": "armazenamento de objetos",
		"filesystem": "sistema de arquivos",
		"pagination": "paginação",
		"offset pagination": "paginação por deslocamento",
		"cursor pagination": "paginação por cursor",
		"throttling": "restrição de taxa",
		"rate limit": "limite de taxa",
		"cache key": "chave de cache",
		"cache entry": "entrada de cache",
		"cache size": "tamanho do cache",
		"versioning": "versionamento",
		"schema validation": "validação de esquema",
		"validator": "validador",
		"validation": "validação",
		"serializer": "serializador",
		"deserializer": "desserializador",
		"middleware stack": "pilha de middleware",
		"job id": "id da tarefa",
		"task id": "id da tarefa",
		"cron job": "tarefa cron",
		"schedule expression": "expressão de agendamento",
		"kernel panic": "pânico do kernel",
		"panic": "pânico",
		"namespace isolation": "isolamento de namespace",
		"healthcheck": "verificação de saúde",
		"bind mount": "montagem vinculada",
		"image id": "id da imagem",
		"container id": "id do contêiner",
		"layer": "camada",
		"layers": "camadas",
		"bridge network": "rede bridge",
		"overlay network": "rede overlay",
		"git hook": "gancho do git",
		"pre-commit": "pre-commit",
		"pre-push": "pre-push",
		"post-merge": "post-merge",
		"remote url": "url remota",
		"upstream": "upstream",
		"origin url": "url do origin",
		"tag name": "nome da tag",
		"branch name": "nome da branch",
		"bare repository": "repositório nu",
		"venv path": "caminho do venv",
		"site-packages": "site-packages",
		"requirements file": "arquivo de requisitos",
		"pip cache": "cache do pip",
		"source distribution": "distribuição de código-fonte",
		"lock file": "arquivo de bloqueio",
		"formatter": "formatador",
		"static analysis": "análise estática",
		"type checker": "verificador de tipos",
		"coverage": "cobertura",
		"unit test": "teste unitário",
		"integration test": "teste de integração",
		"test suite": "suíte de testes",
		"test runner": "executor de testes",
		"assertion": "assertiva",
		"event loop": "loop de eventos",
		"main thread": "thread principal",
		"worker thread": "thread de trabalho",
		"critical section": "seção crítica",
		"hot reload": "recarga a quente",
		"hot restart": "reinício a quente",
		"websocket": "websocket",
		"handshake timeout": "tempo limite do handshake",
		"frame size": "tamanho do quadro",
		"sqli": "injeção sql",
		"open redirect": "redirecionamento aberto",
		"ip whitelist": "lista branca de ip",
		"ip blacklist": "lista negra de ip",
		"allowlist": "lista de permitidos",
		"denylist": "lista de negados",
		"session store": "armazenamento de sessão",
		"load balancer": "balanceador de carga",
		"upstream server": "servidor upstream",
		"health probe": "sonda de saúde",
		"request queue": "fila de requisições",
		"circuit breaker": "disjuntor",
		"fallback": "alternativa",
		"bulkhead": "compartimento",
		"trace span": "span de rastreamento",
		"observability": "observabilidade",
		"telemetry": "telemetria",
		"metric": "métrica",
		"counter": "contador",
		"gauge": "medidor",
		"histogram": "histograma",
		"dashboard": "painel",
		"panel": "painel",
		"namespace conflict": "conflito de namespace",
		"override": "sobrescrever",
		"overridden value": "valor sobrescrito",
		"feature flag": "flag de funcionalidade",
		"rollback plan": "plano de rollback",
		"deployment": "implantação",
		"deploy": "implantar",
		"release": "release",
		"canary": "canário",
		"maintenance": "manutenção",
		"maintenance window": "janela de manutenção",
		"bugfix": "correção de bug",
		"semantic versioning": "versionamento semântico",
		"major": "maior",
		"minor": "menor",
		"patch level": "nível de patch",
		"artifact": "artefato",
		"artifact repository": "repositório de artefatos",
		"pipeline": "pipeline",
		"stage": "estágio",
		"job step": "etapa de tarefa",
		"working directory": "diretório de trabalho",
		"environment variable": "variável de ambiente",
		"secret": "segredo",
		"secrets": "segredos",
		"mask": "mascarar",
		"masked": "mascarado",
		"retry strategy": "estratégia de novas tentativas",
		"quota": "cota",
		"hard limit": "limite rígido",
		"soft limit": "limite flexível",
		"session timeout": "tempo limite de sessão",
		"round-trip time": "tempo de ida e volta",
		"dns cache": "cache de dns",
		"resolver": "resolvedor",
		"trust store": "repositório de confiança",
		"key store": "repositório de chaves",
		"tls version": "versão de tls",
		"cipher suite": "conjunto de cifras",
		"handshake failure": "falha no handshake",
		"gateway timeout": "tempo limite do gateway",
		"service discovery": "descoberta de serviços",
		"upstream timeout": "tempo limite do upstream",
		"body size": "tamanho do corpo",
		"header size": "tamanho do cabeçalho",
		"idle connection": "conexão ociosa",
		"prefetch": "pré-busca",
		"preload": "pré-carregar",
		"warmup": "aquecimento",
		"rolling update": "atualização gradual",
		"replica count": "número de réplicas",
		"cluster ip": "ip de cluster",
		"node port": "porta de nó",
		"service account": "conta de serviço",
		"secret mount": "montagem de segredo",
		"readiness probe": "sonda de prontidão",
		"liveness probe": "sonda de vida",
		"init container": "contêiner de inicialização",
		"sidecar": "sidecar",	"dependency": "dependência",
	"dependencies": "dependências",
	"version": "versão",
	"versions": "versões",
	"lockfile": "arquivo de bloqueio",
	"registry": "registro",
	"virtualenv": "ambiente virtual",
		 "ERROR: unknown command": "ERRO: comando desconhecido",
    "maybe you meant": "talvez você quis dizer",
    "Package": "Pacote",
    "Version": "Versão",
    "Successfully installed": "Instalado com sucesso",
    "Requirement already satisfied": "Dependência já satisfeita",
    "Installing": "Instalando",
    "Uninstalling": "Desinstalando",
    "Updating": "Atualizando",
    "Up-to-date": "Atualizado",
    "Dependency": "Dependência",
    "Module": "Módulo",
    "Command": "Comando",
    "Not recognized": "Não reconhecido",
    "File": "Arquivo",
    "Directory": "Diretório",
    "Permission denied": "Permissão negada",
    "Access denied": "Acesso negado",
    "The term": "O termo",
    "is not recognized": "não é reconhecido",
    "Cannot find path": "Não foi possível encontrar o caminho",
    "Traceback": "Rastreamento de erro",
    "Exception": "Exceção",
    "SyntaxError": "Erro de sintaxe",
    "IndentationError": "Erro de indentação",
    "NameError": "Erro de nome",
    "ImportError": "Erro de importação",
    "ModuleNotFoundError": "Módulo não encontrado",
		"Operation not permitted": "Operação não permitida",
		"Connection refused": "Conexão recusada",
		"Command not found": "Comando não encontrado",
		"No such file or directory": "Arquivo ou diretório inexistente",
		"Operation timed out": "Operação expirou",
		"Invalid argument": "Argumento inválido",
		"Segmentation fault": "Falha de segmentação",
		"Broken pipe": "Pipe quebrado",
		"Read-only file system": "Sistema de arquivos somente leitura",
		"Out of memory": "Memória insuficiente",
		"Device or resource busy": "Dispositivo ou recurso ocupado",
		"Network is unreachable": "Rede inacessível",
		"Connection timed out": "Conexão expirada",
		"Host unreachable": "Host inacessível",
		"Permission error": "Erro de permissão",
		"Unknown error": "Erro desconhecido",
		"Invalid option": "Opção inválida",
		"Invalid command": "Comando inválido",
		"Invalid input": "Entrada inválida",
		"Invalid syntax": "Sintaxe inválida",
		"Invalid path": "Caminho inválido",
		"Path not found": "Caminho não encontrado",
		"Disk full": "Disco cheio",
		"No space left on device": "Sem espaço disponível no dispositivo",
		"Device not ready": "Dispositivo não está pronto",
		"Access is denied": "Acesso negado",
		"Operation aborted": "Operação abortada",
		"Operation failed": "Operação falhou",
		"Operation successful": "Operação bem-sucedida",
		"reset": "redefinida",
		"error": "erro",
		"not": "não",
		"temporarily": "temporariamente",
		"internal": "interno",
		"bad": "inválida",
		"timed": "expirou",
		"already": "já",
		"use": "em uso",
		"in": "em",
		"progress": "andamento",
		"broken": "quebrada",
		"exists": "existe",
		"busy": "ocupado",
		"only": "somente",
		"cannot": "não foi possível",
		"descriptor": "descritor",
		"end": "fim",
		"corrupted": "corrompido",
		"too": "muito",
		"large": "grande",
		"long": "longo",
		"operation": "operação",
		"feature": "funcionalidade",
		"implemented": "implementada",
		"responding": "respondendo",
		"unexpected": "inesperada",
		"checksum": "checksum",
		"data": "dados",
		"parsing": "parsing",
		"decode": "decodificar",
		"encode": "codificar",
		"compilation": "compilação",
		"logical": "lógico",
		"zerodivision": "divisão por zero",
		"warning": "aviso",
		"deprecation": "descontinuação",
		"keyboardinterrupt": "interrupção pelo teclado",
		"systemexit": "saída do sistema",
		"oserror": "sistema operacional",
		"ioerror": "entrada/saída",
		"exited": "finalizado",
		"terminated": "encerrado",
		"killed": "morto",
		"illegal": "ilegal",
		"instruction": "instrução",
		"abort": "aborto",
		"many": "excesso",
		"socket": "socket",
		"unreachable": "inacessível",
		"code": "código",
		"unhandled": "não tratado",
		"exception": "exceção",
		"initialization": "inicialização",
		"state": "estado",
		"concurrency": "concorrência",
		"duplicate": "duplicada",
		"privileges": "privilégios",
		"rate": "limite de requisições",
		"bind": "vincular",
		"listen": "escutar",
		"accept": "aceitar",
		"send": "enviar",
		"receive": "receber",
		"down": "inativo",
		"executed": "executado",
		"nothing": "nada",
		"rejected": "rejeitada",
		"required": "necessária",
		"i/o": "E/S",
		"mount": "montar",
		"violation": "violação",
		"segmentation": "segmentação",
		"bus": "barramento",
		"garbage": "lixo",
		"collection": "coleta",
		"low": "pouca",
		"unicode": "Unicode",
		"character": "caractere",
		"time": "tempo",
		"synchronization": "sincronização",
		"clock": "relógio",
		"skew": "diferença",
		"timestamp": "carimbo",
		"plugin": "plugin",
		"circular": "circular",
		"license": "licença",
		"encryption": "criptografia",
		"decryption": "descriptografia",
		"revoked": "revogado",
		"secure": "segura",
		"sandbox": "sandbox",
		"media": "mídia",
		"codec": "codec",
		"recognized": "reconhecido",
		"redirection": "redirecionamento",
		"temporary": "temporária",
		"permanent": "permanente",
		"lookup": "resolução",
		"resolve": "resolver",
		"forcibly": "à força",
		"negotiation": "negociação",
		"insecure": "insegura",
		"interface": "interface",
		"exhausted": "esgotado",
		"elevation": "elevação",
		"drive": "unidade",
		"sharing": "compartilhamento",
		"specified": "especificado",
		"ready": "pronto",
		"fatal": "fatal",
		"critical": "crítico",
		"core": "core",
		"dumped": "gerado",
		"refs": "refs",
		"working": "árvore de trabalho",
		"clean": "limpa",
		"detached": "destacado",
		"manifest": "manifesto",
		"entry": "entrada",
		"foreign": "estrangeira",
		"unique": "unico",
		"check": "verificação",
		"satisfies": "satisfaça",
		"errno": "errno",
		"enoent": "inexistente",
		"peer": "par",
		"elifecycle": "ELIFECYCLE",
		"eaccess": "EACCES",
		"eaddrinuse": "EADDRINUSE",
		"enotfound": "ENOTFOUND",
		"coroutine": "coroutine",
		"recursion": "recursão",
		"depth": "profundidade",
		"referenced": "referenciada",
		"assignment": "atribuição",
		"import": "importar",
		"indented": "indentado",
		"block": "bloco",
		"eol": "fim de linha",
		"literal": "literal",
		"unterminated": "não terminada",
		"changed": "mudou",
		"iteration": "iteração",
		"nonetype": "NoneType",
		"subscriptable": "indexável",
		"operand": "operando",
		"serializable": "serializável",
		"attribute error": "erro de atributo",
		"key error": "erro de chave",
		"type error": "erro de tipo",
		"value error": "erro de valor",
		"index error": "erro de índice",
		"stop iteration": "parar iteração",
		"assertion error": "erro de afirmação",
		"unbound local": "local não vinculado",
		"unhashable type": "tipo não hashável",
		"object has no attribute": "objeto não tem atributo",
		"list index out of range": "índice de lista fora do intervalo",
		"dict key error": "erro de chave do dicionário",
		"str object is not callable": "str não é chamável",
		"int object is not subscriptable": "int não é indexável",
		"float object has no attribute": "float não tem atributo",
		"tuple object does not support": "tupla não suporta",
		"set object has no attribute": "set não tem atributo",
		"bytes object is not callable": "bytes não é chamável",
		"module object has no attribute": "módulo não tem atributo",
		"function object is not subscriptable": "função não é indexável",
		"method object is not subscriptable": "método não é indexável",
		"class object is not subscriptable": "classe não é indexável",
		"generator object has no attribute": "gerador não tem atributo",
		"context manager": "gerenciador de contexto",
		"with statement": "instrução with",
		"finally block": "bloco finally",
		"try except": "tentar exceto",
		"raise exception": "levantar exceção",
		"catch exception": "capturar exceção",
		"handle error": "tratar erro",
		"error handler": "tratador de erro",
		"fallback handler": "tratador reserva",
		"rescue block": "bloco de resgate",
		"syntax error": "erro de sintaxe",
		"tab error": "erro de tabulação",
		"unexpected eof": "fim inesperado",
		"unexpected indent": "indentação inesperada",
		"mixed tabs spaces": "tabs e espaços misturados",
		"invalid syntax": "sintaxe inválida",
		"invalid character": "caractere inválido",
		"eol while scanning": "fim de linha escaneando",
		"unclosed string": "string não fechada",
		"unclosed parenthesis": "parêntese não fechado",
		"unterminated string": "string não terminada",
		"invalid escape sequence": "sequência de escape inválida",
		"name already defined": "nome já definido",
		"global variable": "variável global",
		"local variable": "variável local",
		"nonlocal keyword": "palavra-chave nonlocal",
		"closure": "fechamento",
		"free variable": "variável livre",
		"scope resolution": "resolução de escopo",
		"lexical scope": "escopo léxico",
		"dynamic scope": "escopo dinâmico",
		"import error": "erro de importação",
		"cannot import": "não foi possível importar",
		"module not found": "módulo não encontrado",
		"circular import": "importação circular",
		"relative import": "importação relativa",
		"absolute import": "importação absoluta",
		"from import": "do import",
		"import as": "importar como",
		"wildcard import": "importação curinga",
		"__init__.py": "arquivo init py",
		"package not found": "pacote não encontrado",
		"namespace package": "pacote namespace",
		"zip import": "importação zip",
		"egg file": "arquivo egg",
		"wheel file": "arquivo wheel",
		"dist info": "info de distribuição",
		"entry point": "ponto de entrada",
		"console script": "script de console",
		"setup.py": "setup py",
		"pyproject.toml": "pyproject toml",
		"requirements.txt": "requirements txt",
		"constraint file": "arquivo de restrições",
		"editable install": "instalação editável",
		"development install": "instalação de desenvolvimento",
		"user install": "instalação de usuário",
		"system install": "instalação do sistema",
		"virtual environment": "ambiente virtual",
		"conda environment": "ambiente conda",
		"base environment": "ambiente base",
		"activate": "ativar",
		"deactivate": "desativar",
		"path not found": "caminho não encontrado",
		"directory not empty": "diretório não vazio",
		"file exists": "arquivo existe",
		"file not found": "arquivo não encontrado",
		"permission denied": "permissão negada",
		"operation not permitted": "operação não permitida",
		"no such device": "dispositivo inexistente",
		"no such file": "arquivo inexistente",
		"not a directory": "não é diretório",
		"is a directory": "é um diretório",
		"invalid argument": "argumento inválido",
		"I/O error": "erro de E/S",
		"no space left": "sem espaço restante",
		"disk quota exceeded": "cota de disco excedida",
		"read only file system": "sistema de arquivos somente leitura",
		"file too large": "arquivo muito grande",
		"filename too long": "nome de arquivo muito longo",
		"path too long": "caminho muito longo",
		"cross device link": "link entre dispositivos",
		"stale file handle": "handle de arquivo obsoleto",
		"too many links": "muitos links",
		"no lock available": "nenhum bloqueio disponível",
		"function not implemented": "função não implementada",
		"too many open files": "muitos arquivos abertos",
		"too many open files in system": "muitos arquivos abertos no sistema",
		"file table overflow": "overflow da tabela de arquivos",
		"no filesystem buffers": "nenhum buffer de sistema de arquivos",
		"resource temporarily unavailable": "recurso temporariamente indisponível",
		"connection reset": "conexão resetada",
		"connection aborted": "conexão abortada",
		"connection refused": "conexão recusada",
		"network unreachable": "rede inacessível",
		"host unreachable": "host inacessível",
		"connection timed out": "conexão expirou",
		"operation timed out": "operação expirou",
		"broken pipe": "pipe quebrado",
		"software caused connection abort": "software causou aborto de conexão",
		"destination address required": "endereço de destino requerido",
		"message too long": "mensagem muito longa",
		"protocol wrong type": "protocolo tipo errado",
		"protocol not available": "protocolo não disponível",
		"protocol not supported": "protocolo não suportado",
		"socket type not supported": "tipo de socket não suportado",
		"not supported": "não suportado",
		"operation not supported": "operação não suportada",
		"address family not supported": "família de endereço não suportada",
		"address already in use": "endereço já em uso",
		"cannot assign requested address": "não foi possível atribuir endereço solicitado",
		"network down": "rede inativa",
		"network dropped connection": "rede descartou conexão",
		"software loopback config error": "erro de config loopback software",
		"connection already in progress": "conexão já em progresso",
		"operation already in progress": "operação já em progresso",
		"stale network file handle": "handle de arquivo de rede obsoleto",
		"remote I/O error": "erro de E/S remoto",
		"quota exceeded": "cota excedida",
		"no medium found": "nenhum meio encontrado",
		"wrong medium type": "tipo de meio errado",
		"no data available": "nenhum dado disponível",
		"device timeout": "timeout do dispositivo",
		"out of memory": "sem memória",
		"operation would block": "operação bloquearia",
		"interrupt": "interrompido",
		"bad message": "mensagem ruim",
		"file descriptor in bad state": "descritor de arquivo em mau estado",
		"not a socket": "não é socket",
		"destination address unreachable": "endereço de destino inacessível",
		"message size": "tamanho da mensagem",
		"protocol error": "erro de protocolo",
		"multicast group full": "grupo multicast cheio",
		"socket operation on non-socket": "operação de socket em não-socket",
		"destination port unreachable": "porta de destino inacessível",
		"address family not supported by protocol family": "família de endereço não suportada pela família de protocolo",
		"address already in use by another socket": "endereço já em uso por outro socket",
		"no buffer space available": "nenhum espaço de buffer disponível",
		"transport endpoint is not connected": "ponto final de transporte não conectado",
		"no route to host": "nenhuma rota para host",
		"operation canceled": "operação cancelada",
		"socket is already connected": "socket já conectado",
		"socket is not connected": "socket não conectado",
		"cannot send after socket shutdown": "não foi possível enviar após shutdown do socket",
		"too many references": "muitas referências",
		"operation on closed socket": "operação em socket fechado",
		"fd is not socket": "fd não é socket",
		"fd is not an open file": "fd não é arquivo aberto",
		"socket too large": "socket muito grande",
		"wrong protocol type": "tipo de protocolo errado",
		"protocol option not supported": "opção de protocolo não suportada",
		"operation not supported on socket": "operação não suportada em socket",
		"protocol family not supported": "família de protocolo não suportada",
		"address not available": "endereço não disponível",
		"network interface is not configured": "interface de rede não configurada",
		"attributeerror": "erro de atributo",
		"keyerror": "erro de chave",
		"typeerror": "erro de tipo",
		"valueerror": "erro de valor",
		"indexerror": "erro de índice",
		"stopiteration": "parar iteração",
		"assertionerror": "erro de afirmação",
		"unboundlocalerror": "local não vinculado",
		"unhashabletype": "não hashável",
		"listindexoutofrange": "índice fora intervalo",
		"strnotcallable": "str não chamável",
		"intnotsubscriptable": "int não indexável",
		"floatnoattribute": "float sem atributo",
		"tupleobjectdoesnotsupport": "tupla não suporta",
		"setnoattribute": "set sem atributo",
		"bytesnotcallable": "bytes não chamável",
		"modulenoattribute": "módulo sem atributo",
		"contextmanager": "gerenciador contexto",
		"withstatement": "instrução with",
		"finallyblock": "bloco finally",
		"tryexcept": "tentar exceto",
		"raiseexception": "levantar exceção",
		"catchexception": "capturar exceção",
		"re-raise": "re-levantar",
		"propagate": "propagar",
		"handleerror": "tratar erro",
		"errorhandler": "tratador erro",
		"fallbackhandler": "tratador reserva",
		"syntaxerror": "erro sintaxe",
		"taborerror": "erro tabulação",
		"unexpectedeof": "fim inesperado",
		"unexpectedindent": "indentação inesperada",
		"mixedtabspaces": "tabs espaços misturados",
		"invalidcharacter": "caractere inválido",
		"eolwhilescanning": "fim linha escaneando",
		"unclosedstring": "string não fechada",
		"unclosedparenthesis": "parêntese não fechado",
		"unterminatedstring": "string não terminada",
		"invalidescapes": "escape inválido",
		"namealreadydefined": "nome já definido",
		"redefinition": "redefinição",
		"redeclared": "redeclarado",
		"shadowing": "sombreamento",
		"globalvariable": "variável global",
		"localvariable": "variável local",
		"nonlocalkeyword": "nonlocal",
		"freevariable": "variável livre",
		"scoperesolution": "resolução escopo",
		"lexicalscope": "escopo léxico",
		"importerror": "erro importação",
		"cannotimport": "não importar",
		"modulenotfound": "módulo não encontrado",
		"circularimport": "import circular",
		"relativeimport": "import relativo",
		"absoluteimport": "import absoluto",
		"fromimport": "do import",
		"importas": "importar como",
		"wildcardimport": "import curinga",
		"initpy": "init py",
		"packagenotfound": "pacote não encontrado",
		"namespacepackage": "pacote namespace",
		"zipimport": "import zip",
		"eggfile": "arquivo egg",
		"wheelfile": "arquivo wheel",
		"distinfo": "info distribuição",
		"metadata": "metadados",
		"entrypoint": "ponto entrada",
		"consolescript": "script console",
		"setuppy": "setup py",
		"pyprojecttoml": "pyproject toml",
		"constraintfile": "arquivo restrições",
		"editableinstall": "instalação editável",
		"developmentinstall": "instalação desenvolvimento",
		"userinstall": "instalação usuário",
		"systeminstall": "instalação sistema",
		"virtualenvironment": "ambiente virtual",
		"condaenvironment": "ambiente conda",
		"baseenvironment": "ambiente base",
		"permissiondenied": "permissão negada",
		"operationnotpermitted": "operação não permitida",
		"nosuchdevice": "dispositivo inexistente",
		"nosuchfile": "arquivo inexistente",
		"notadirectory": "não é diretório",
		"isadirectory": "é diretório",
		"invalidargument": "argumento inválido",
		"noerror": "erro E/S",
		"nospaceleft": "sem espaço",
		"diskquotaexceeded": "cota disco excedida",
		"readonlyfilesystem": "somente leitura",
		"filetoolarge": "arquivo grande",
		"filenametoolong": "nome arquivo longo",
		"pathtoolong": "caminho longo",
		"crossdevicelink": "link dispositivos",
		"stalefilehandle": "handle arquivo obsoleto",
		"toomanylinks": "muitos links",
		"nclockavailable": "sem bloqueio",
		"functionnotimplemented": "função não implementada",
		"directorynotempty": "diretório não vazio",
		"toomanyopenfiles": "muitos arquivos abertos",
		"filetableoverflow": "overflow tabela arquivos",
		"nofilesystembuffers": "sem buffer arquivos",
		"resourcetemporarilyunavailable": "recurso indisponível",
		"connectionreset": "conexão resetada",
		"connectionaborted": "conexão abortada",
		"connectionrefused": "conexão recusada",
		"networkunreachable": "rede inacessível",
		"hostunreachable": "host inacessível",
		"connectiontimedout": "conexão expirou",
		"operationtimedout": "operação expirou",
		"brokenpipe": "pipe quebrado",
		"softwarecausedconnectionabort": "software abortou conexão",
		"destinationaddressrequired": "endereço destino requerido",
		"messagetoolong": "mensagem longa",
		"protocolwrongtype": "protocolo tipo errado",
		"protocolnotavailable": "protocolo indisponível",
		"protocolnotsupported": "protocolo não suportado",
		"sockettypenotsupported": "socket não suportado",
		"notsupported": "não suportado",
		"operationnotsupported": "operação não suportada",
		"addressfamilynotsupported": "endereço não suportado",
		"addressalreadyinuse": "endereço em uso",
		"cannotassignrequestedaddress": "não atribuir endereço",
		"networkdown": "rede inativa",
		"networkdroppedconnection": "rede descartou conexão",
		"connectionalreadyinprogress": "conexão em progresso",
		"operationalreadyinprogress": "operação em progresso",
		"stalenetworkfilehandle": "handle rede obsoleto",
		"remoteioerror": "E/S remoto",
		"quotaexceeded": "cota excedida",
		"nomediumfound": "sem meio encontrado",
		"wrongmediumtype": "meio errado",
		"nodataavailable": "sem dados",
		"devicetimeout": "timeout dispositivo",
		"outofmemory": "sem memória",
		"operationwouldblock": "operação bloquearia",
		"badmessage": "mensagem ruim",
		"filedescriptorbadstate": "descritor mau estado",
		"destinationportunreachable": "porta fora",
		"protocolfamily": "família protocolo",
		"nobufferspace": "buffer lotado",
		"transportendpoint": "transporte final",
		"noroutetohost": "sem rota host",
		"operationcanceled": "operação cancelada",
		"socketalreadyconnected": "socket conectado",
		"socketnotconnected": "socket desconectado",
		"cannotsendaftershutdown": "envio negado",
		"fdnotsocket": "fd não socket",
		"fdnotopenfile": "fd não aberto",
		"sockettoolarge": "socket gigante",
		"wrongprotocoltype": "protocolo tipo errado",
		"protocoloption": "opção protocolo",
		"deadlockdetected": "bloqueio mútuo",
		"memoryleak": "vazamento memória",
		"segfault": "falha memória",
		"buserror": "erro barramento",
		"stackoverflow": "pilha esgotada",
		"heapcorruption": "montículo corrompido",
		"doublefree": "dupla liberação",
		"useafterfree": "uso pós liberação",
		"bufferoverflow": "transbordamento buffer",
		"formatstring": "formato vulnerável",
		"integeroverflow": "transbordamento inteiro",
		"offbyone": "erro unidade",
		"racecondition": "corrida condição",
		"threaddeadlock": "deadlock threads",
		"readwritelock": "bloqueio leitura escrita",
		"semaphorewait": "espera semáforo",
		"conditionvariable": "variável condição",
		"epoll": "epoll multiplexador",
		"kqueue": "kqueue multiplexador",
		"inotify": "inotify monitor",
		"signalfd": "signal arquivo",
		"timerfd": "timer arquivo",
		"eventfd": "event arquivo",
		"unixsocket": "socket unix",
		"seqpacket": "pacote sequencial",
		"rawsocket": "socket cru",
		"systemd": "systemd init",
		"dbus": "dbus barramento",
		"journald": "journald logs",
		"coredump": "dump memória",
		"oomkiller": "assassino memória",
		"cgroups": "grupos controle",
		"seccomp": "seccomp filtros",
		"apparmor": "apparmor segurança",
		"selinux": "selinux segurança",
		"auditd": "auditd auditoria",
		"sysdig": "sysdig monitoramento",
		"bpftrace": "bpftrace rastreamento",
		"ebpf": "ebpf kernel",
		"kprobe": "kprobe kernel",
		"uprobe": "uprobe usuário",
		"tracepoint": "ponto rastreamento",
		"functiongraph": "gráfico funções",
		"powerpc": "powerpc arquitetura",
		"riscv": "riscv arquitetura",
		"aarch64": "aarch64 arquitetura",
		"s390x": "s390x arquitetura",
		"ppc64le": "ppc64le little endian",
		"loongarch": "loongarch arquitetura",
		"hexagon": "hexagon arquitetura",
		"llvm": "llvm compilador",
		"clang": "clang compilador",
		"quickjs": "quickjs engine",
		"spidermonkey": "spidermonkey engine",
		"d8": "d8 shell",
		"wasmer": "wasmer runtime",
		"wasmtime": "wasmtime runtime",
		"wasm3": "wasm3 runtime",
		"webassembly": "webassembly",
		"wit": "wit interface",
		"wasip1": "wasip1 preview",
		"wasip2": "wasip2 preview",
		"syscall": "chamada sistema",
		"clone3": "clone3 processo",
		"openat2": "openat2 arquivo",
		"statx": "statx estatísticas",
		"umount2": "umount2 desmontar",
		"fuse": "fuse usuário",
		"fuse3": "fuse3 usuário",
		"virtiofs": "virtiofs compartilhamento",
		"9p": "9p protocolo",
		"ceph": "ceph distribuído",
		"gluster": "gluster distribuído",
		"lustre": "lustre paralelo",
		"beegfs": "beegfs paralelo",
		"orange": "orange fs",
		"gpfs": "gpfs ibm",
		"v9fs": "v9fs virtio",
		"qcow2": "qcow2 disco",
		"vmdk": "vmdk vmware",
		"vpc": "vpc virtual",
		"vhd": "vhd virtual",
		"vhdx": "vhdx virtual",
		"luks": "luks criptografia",
		"dmcrypt": "dm crypt",
		"lvm": "lvm volumes",
		"btrfs": "btrfs cópias",
		"zfs": "zfs snapshots",
		"xfs": "xfs escalável",
		"ext4": "ext4 journal",
		"ext3": "ext3 journal",
		"ext2": "ext2 tradicional",
		"jfs": "jfs ibm",
		"reiserfs": "reiserfs jornal",
		"minix": "minix antigo",
		"msdos": "msdos compatível",
		"vfat": "vfat fat32",
		"exfat": "exfat microsoft",
		"ntfs": "ntfs windows",
		"hfs": "hfs mac",
		"hfsplus": "hfsplus mac",
		"udf": "udf dvd",
		"iso9660": "iso9660 cdrom",
		"overlayfs": "overlayfs unificado",
		"tmpfs": "tmpfs ram",
		"ramfs": "ramfs ram",
		"hugetlbfs": "huge páginas",
		"proc": "proc processos",
		"sysfs": "sysfs sistema",
		"debugfs": "debugfs debug",
		"tracefs": "tracefs rastreamento",
		"configfs": "configfs configuração",
		"devpts": "devpts terminais",
		"devtmpfs": "devtmpfs dispositivos",
		"pstore": "pstore persistente",
		"binderfs": "binderfs android",
		"rpcpipefs": "rpc pipe",
		"cgroup": "cgroup controle",
		"cgroup2": "cgroup2 unificado",
		"valgrind": "valgrind debug",
		"addresssanitizer": "asan detector",
		"threadsanitizer": "tsan threads",
		"undefinedbehavior": "ubsan indefinido",
		"leakcheck": "verificação vazamentos",
		"callgrind": "callgrind perfilador",
		"cachegrind": "cachegrind cache",
		"helgrind": "helgrind threads",
		"drd": "drd detector",
		"memcheck": "memcheck memória",
		"gdb": "gdb debug",
		"lldb": "lldb debug",
		"strace": "strace syscalls",
		"ltrace": "ltrace bibliotecas",
		"perf": "perf performance",
		"flamegraph": "flamegraph chamas",
		"blocker": "bloqueador",
		"brlock": "brlock bloqueio",
		"condvar": "condvar condição",
		"futexwait": "futex espera",
		"park": "park thread",
		"unpark": "unpark thread",
		"yield": "yield processador",
		"sched_yield": "sched yield",
		"preempt": "preempt interrupção",
		"migration": "migração cpu",
		"affinity": "afinidade cpu",
		"cputimer": "timer cpu",
		"itimer": "itimer intervalo",
		"posix_timer": "posix timer",
		"realtime": "tempo real",
		"softirq": "softirq interrupção",
		"hardirq": "hardirq interrupção",
		"tasklet": "tasklet diferido",
		"workqueue": "fila trabalho",
		"kthread": "kernel thread",
		"work_struct": "estrutura trabalho",
		"delayed_work": "trabalho atrasado",
		"timer_list": "lista timers",
		"hrtimer": "timer alta resolução",
		"posix_clock": "posix relógio",
		"clock_gettime": "obter tempo",
		"clock_nanosleep": "sono nanossegundos",
		"futex": "futex primitiva",
		"robust_list": "lista robusta",
		"pi_futex": "futex prioridade",
		"wait_queue": "fila espera",
		"wake_up": "acordar",
		"wake_up_all": "acordar todos",
		"schedule_timeout": "agendar timeout",
		"try_to_wake_up": "tentar acordar",
		"select_task_rq": "selecionar cpu",
		"pick_next_task": "próxima tarefa",
		"put_prev_task": "tarefa anterior",
		"context_switch": "troca contexto",
		"voluntary": "troca voluntária",
		"involuntary": "troca involuntária",
		"reschedule": "reagendar",
		"need_resched": "precisa reagendar",
		"tif_need_resched": "flag reagendar",
		"irq_disable": "desabilitar interrupção",
		"irq_enable": "habilitar interrupção",
		"sti": "sti interrupção",
		"local_irq": "irq local",
		"preempt_disable": "desabilitar preempt",
		"preempt_enable": "habilitar preempt",
		"spin_lock": "spinlock bloqueio",
		"spin_unlock": "spinlock liberar",
		"rwlock": "rwlock leitura",
		"mutex_lock": "mutex bloqueio",
		"mutex_unlock": "mutex liberar",
		"semaphore_down": "semáforo baixo",
		"semaphore_up": "semáforo cima",
		"completion": "completion espera",
		"wait_for_completion": "esperar conclusão",
		"complete": "concluir",
		"reinit_completion": "reiniciar conclusão",
		"rwsem": "rwsem leitor",
		"down_read": "ler bloqueio",
		"down_write": "escrever bloqueio",
		"up_read": "ler liberar",
		"up_write": "escrever liberar",
		"lockdep": "lockdep verificador",
		"lock_validator": "validador bloqueios",
		"circular_wait": "espera circular",
		"lock_chain": "cadeia bloqueios",
		"lock_class": "classe bloqueio",
		"lockdep_map": "mapa lockdep",
		"hardirq_context": "contexto hardirq",
		"softirq_context": "contexto softirq",
		"irq_context": "contexto irq",
		"atomic_context": "contexto atômico",
		"preempt_context": "contexto preempt",
		"rcu_read_lock": "rcu leitura",
		"rcu_read_unlock": "rcu liberar",
		"rcu_synchronize": "rcu sincronizar",
		"call_rcu": "chamar rcu",
		"grace_period": "período graça",
		"quiescent_state": "estado quiescente",
		"rcu_barrier": "barreira rcu",
		"smp_call_function": "chamar smp",
		"ipi": "ipi interrupção",
		"cross_call": "chamada cruzada",
		"smp_affinity": "smp afinidade",
		"numa": "numa memória",
		"node": "nó memória",
		"memory_node": "nó memória",
		"zone": "zona memória",
		"dma_zone": "zona dma",
		"normal_zone": "zona normal",
		"highmem_zone": "zona alta memória",
		"movable_zone": "zona móvel",
		"page": "página memória",
		"pagecache": "cache páginas",
		"anon_page": "página anônima",
		"swapcache": "cache swap",
		"dirty_page": "página suja",
		"clean_page": "página limpa",
		"locked_page": "página bloqueada",
		"private_page": "página privada",
		"slab_page": "página slab",
		"slab": "slab alocador",
		"slub": "slub alocador",
		"sLOB": "slob alocador",
		"kmalloc": "kmalloc kernel",
		"kfree": "kfree kernel",
		"vzalloc": "vzalloc virtual",
		"vmalloc": "vmalloc virtual",
		"krealloc": "krealloc kernel",
		"get_free_pages": "páginas livres",
		"__get_free_pages": "páginas livres kernel",
		"alloc_pages": "alocar páginas",
		"__get_dma_pages": "dma páginas",
		"page_frag": "fragmento página",
		"compound_page": "página composta",
		"transparent_hugepage": "hugepage transparente",
		"thp": "thp transparente",
		"split_huge_page": "dividir hugepage",
		"collapse_huge_page": "colapsar hugepage",
		"khugepaged": "khugepaged daemon",
		"memory_compaction": "compactação memória",
		"page_reclaim": "recuperação páginas",
		"kswapd": "kswapd recuperador",
		"direct_reclaim": "recuperação direta",
		"vmscan": "vmscan scanner",
		"lru_list": "lista lru",
		"active_list": "lista ativa",
		"inactive_list": "lista inativa",
		"unevictable_list": "lista irremovível",
		"shrinker": "shrinker redutor",
		"shrink_slab": "reduzir slab",
		"oom": "oom killer",
		"oom_score": "pontuação oom",
		"oom_adj": "ajuste oom",
		"lowmem_reserve": "reserva baixa memória",
		"min_free_kbytes": "kb livres mínimo",
		"watermark_scale_factor": "fator escala marca",
		"page_alloc": "alocador páginas",
		"__alloc_pages": "alocar páginas kernel",
		"gfp_flags": "flags alocação",
		"gfp_kernel": "kernel alocação",
		"gfp_atomic": "atômica alocação",
		"gfp_highuser": "usuário alto",
		"gfp_user": "usuário alocação",
		"gfp_dma": "dma alocação",
		"gfp_highmem": "alta memória",
		"__gfp_io": "io alocação",
		"__gfp_fs": "filesystem alocação",
		"__gfp_direct_reclaim": "reclaim direto",
		"__gfp_kswapd_reclaim": "kswapd reclaim",
		"__gfp_memalloc": "memalloc alocação",
		"__gfp_noretry": "sem retry",
		"__gfp_no_fail": "sem falha",
		"__gfp_nomap": "sem mapear",
		"__gfp_atomic": "atômico kernel",

	}

