import re


def traduzir_saida(saida) -> str:
	saida = str(saida).replace('_',' ').replace('-',' ')
	if not isinstance(saida, str):
		if hasattr(saida, 'strerror'):
			saida = saida.strerror or str(saida)
		elif hasattr(saida, 'msg'):
			saida = saida.msg or str(saida)
		else:
			saida = str(saida)

	saida_original = saida
	saida_lower = saida.lower()

	for en, pt in TRANSLATE_MAP().items():
		pattern = r'\b' + re.escape(en.lower()) + r'\b'
		saida_lower = re.sub(pattern, pt.lower(), saida_lower)

	if saida_original.isupper():
		return saida_lower.upper()
	elif saida_original.istitle():
		return saida_lower.title()

	return str(saida_lower).capitalize()


def TRANSLATE_MAP():
	# Exemplo de dicionário
	return {
	"is not defined":"não está definido!",
	"errors": "erros",
	"warnings": "avisos",
	"failed": "falhou",
	"failure": "falha",
	"success": "sucesso",
	"successful": "bem-sucedido",
	"unknown": "desconhecido",
	"invalid": "inválido",
	"valid": "válido",
	"missing": "ausente",
	"found": "encontrado",
	"not found": "não encontrado",
	"empty": "vazio",
	"loaded": "carregado",
	"loading": "carregando",
	"unloaded": "descarregado",
	"started": "iniciado",
	"starting": "iniciando",
	"stopped": "parado",
	"stopping": "parando",
	"running": "em execução",
	"finished": "finalizado",
	"completed": "concluído",
	"aborted": "abortado",
	"cancelled": "cancelado",
	"denied": "negado",
	"refused": "recusado",
	"forbidden": "proibido",
	"allowed": "permitido",
	"available": "disponível",
	"unavailable": "indisponível",
	"supported": "suportado",
	"unsupported": "não suportado",
	"enabled": "ativado",
	"disabled": "desativado",
	"timeout": "tempo limite",
	"expired": "expirado",
	"retry": "tentar novamente",
	"retries": "tentativas",
	"limit": "limite",
	"exceeded": "excedido",
	"overridden": "sobrescrito",
	"default": "padrão",
	"custom": "personalizado",

	"file": "arquivo",
	"files": "arquivos",
	"folder": "pasta",
	"folders": "pastas",
	"directory": "diretório",
	"directories": "diretórios",
	"path": "caminho",
	"paths": "caminhos",
	"name": "nome",
	"names": "nomes",
	"extension": "extensão",
	"size": "tamanho",
	"sizes": "tamanhos",
	"modified": "modificado",
	"created": "criado",
	"deleted": "excluído",
	"remove": "remover",
	"removed": "removido",
	"rename": "renomear",
	"renamed": "renomeado",
	"copy": "copiar",
	"copied": "copiado",
	"move": "mover",
	"moved": "movido",
	"read": "ler",
	"write": "escrever",
	"written": "escrito",
	"execute": "executar",
	"executable": "executável",
	"append": "acrescentar",
	"open": "abrir",
	"opened": "aberto",
	"close": "fechar",
	"closed": "fechado",
	"save": "salvar",
	"saved": "salvo",
	"symlink": "link simbólico",
	"hardlink": "link físico",

	"permission": "permissão",
	"permissions": "permissões",
	"access": "acesso",
	"owner": "dono",
	"group": "grupo",
	"others": "outros",
	"read-only": "somente leitura",
	"read-write": "leitura e escrita",
	"locked": "bloqueado",
	"unlocked": "desbloqueado",
	"restricted": "restrito",
	"privileged": "com privilégios",
	"unprivileged": "sem privilégios",
	"admin": "admin",
	"administrator": "administrador",
	"root": "root",
	"user": "usuário",
	"users": "usuários",
	"guest": "convidado",
	"session": "sessão",
	"sessions": "sessões",
	"login": "login",
	"logout": "logout",
	"authenticated": "autenticado",
	"unauthenticated": "não autenticado",
	"authorized": "autorizado",
	"unauthorized": "não autorizado",
	"password": "senha",
	"username": "nome de usuário",
	"credentials": "credenciais",
	"key": "chave",
	"keys": "chaves",
	"certificate": "certificado",
	"certificates": "certificados",
	"signature": "assinatura",

	"connection": "conexão",
	"connections": "conexões",
	"connected": "conectado",
	"disconnected": "desconectado",
	"offline": "offline",
	"online": "online",
	"host": "host",
	"hosts": "hosts",
	"server": "servidor",
	"servers": "servidores",
	"client": "cliente",
	"clients": "clientes",
	"address": "endereço",
	"addresses": "endereços",
	"ip": "ip",
	"port": "porta",
	"ports": "portas",
	"protocol": "protocolo",
	"protocols": "protocolos",
	"request": "requisição",
	"requests": "requisições",
	"response": "resposta",
	"responses": "respostas",
	"status": "status",
	"latency": "latência",
	"bandwidth": "largura de banda",
	"throughput": "taxa de transferência",
	"packet": "pacote",
	"packets": "pacotes",
	"firewall": "firewall",
	"proxy": "proxy",
	"gateway": "gateway",
	"router": "roteador",
	"dns": "dns",
	"domain": "domínio",
	"ssl": "ssl",
	"tls": "tls",
	"handshake": "handshake",
	"timeouted": "expirado",
	"retrying": "re-tentando",

	"system": "sistema",
	"kernel": "kernel",
	"process": "processo",
	"processes": "processos",
	"thread": "thread",
	"threads": "threads",
	"service": "serviço",
	"services": "serviços",
	"signal": "sinal",
	"signals": "sinais",
	"cpu": "cpu",
	"memory": "memória",
	"ram": "ram",
	"swap": "swap",
	"disk": "disco",
	"disks": "discos",
	"volumes": "volumes",
	"partition": "partição",
	"partitions": "partições",
	"device": "dispositivo",
	"devices": "dispositivos",
	"driver": "driver",
	"drivers": "drivers",
	"hardware": "hardware",
	"software": "software",
	"resource": "recurso",
	"resources": "recursos",
	"limits": "limites",
	"architecture": "arquitetura",
	"platform": "plataforma",
	"environment": "ambiente",
	"variable": "variável",
	"variables": "variáveis",
	"locale": "localidade",
	"encoding": "codificação",
	"decoding": "decodificação",

	"python": "python",
	"module": "módulo",
	"modules": "módulos",
	"package": "pacote",
	"packages": "pacotes",
	"library": "biblioteca",
	"libraries": "bibliotecas",
	"script": "script",
	"scripts": "scripts",
	"function": "função",
	"functions": "funções",
	"class": "classe",
	"classes": "classes",
	"argument": "argumento",
	"arguments": "argumentos",
	"parameter": "parâmetro",
	"parameters": "parâmetros",
	"returns": "retornos",
	"value": "valor",
	"values": "valores",
	"type": "tipo",
	"types": "tipos",
	"instance": "instância",
	"instances": "instâncias",
	"object": "objeto",
	"objects": "objetos",
	"attribute": "atributo",
	"attributes": "atributos",
	"property": "propriedade",
	"properties": "propriedades",
	"iterator": "iterador",
	"iterable": "iterável",
	"list": "lista",
	"lists": "listas",
	"tuple": "tupla",
	"tuples": "tuplas",
	"dict": "dicionário",
	"dictionary": "dicionário",
	"set": "conjunto",
	"sets": "conjuntos",
	"string": "string",
	"strings": "strings",
	"bytes": "bytes",
	"bool": "booleano",
	"boolean": "booleano",
	"int": "inteiro",
	"should" : "deve",
	"be" : "ser",
	"float": "ponto flutuante",
	"or":'ou',
	"and":'e',
	"git": "git",
	"repository": "repositório",
	"repositories": "repositórios",
	"branch": "branch",
	"branches": "branches",
	"tag": "tag",
	"tags": "tags",
	"commits": "commits",
	"merge": "merge",
	"rebase": "rebase",
		"pull": "puxar",
		"push": "enviar",
	"fetch": "fetch",
	"clone": "clonar",
	"origin": "original",
	"remote": "remoto",
	"stash": "stash",
	"staged": "preparado",
	"conflict": "conflito",
	"conflicts": "conflitos",
	"diff": "diff",
	"history": "histórico",

	"docker": "docker",
	"container": "contêiner",
	"containers": "contêineres",
	"image": "imagem",
	"images": "imagens",
	"volume": "volume",
	"network": "rede",
	"compose": "compose",
	"daemon": "daemon",
	"tagged": "tagueado",
	"built": "construído",
	"run": "executar",
	"exec": "exec",
	"attach": "anexar",
	"detach": "desanexar",
	"inspect": "inspecionar",

	"database": "banco de dados",
	"databases": "bancos de dados",
	"table": "tabela",
	"tables": "tabelas",
	"row": "linha",
	"rows": "linhas",
	"columns": "colunas",
	"record": "registro",
	"records": "registros",
	"index": "índice",
	"indexes": "índices",
	"query": "consulta",
	"queries": "consultas",
	"transaction": "transação",
	"transactions": "transações",
	"commit": "commit",
	"rollback": "rollback",
	"schema": "esquema",
	"schemas": "esquemas",
	"constraint": "restrição",
	"constraints": "restrições",
	"cursor": "cursor",
	"connection pool": "pool de conexões",
		"crash": "travamento",
		"crashed": "travou",
		"hang": "congelar",
		"hanged": "congelado",
		"freeze": "congelar",
		"frozen": "congelado",
		"bug": "bug",
		"bugs": "bugs",
		"issue": "problema",
		"issues": "problemas",
		"problem": "problema",
		"problems": "problemas",
		"fix": "corrigir",
		"fixed": "corrigido",
		"patched": "corrigido",
		"workaround": "solução alternativa",
		"debugging": "depuração",
		"trace": "rastro",
		"traceback": "rastreamento",
		"frame": "quadro",
		"frames": "quadros",
		"line": "linha",
		"lines": "linhas",
		"column": "coluna",
		"offset": "deslocamento",
		"source": "fonte",
		"source code": "código-fonte",

		"compile": "compilar",
		"compiled": "compilado",
		"compiler": "compilador",
		"interpreted": "interpretado",
		"interpreter": "interpretador",
		"runtime": "tempo de execução",
		"build": "compilação",
		"optimize": "otimizar",
		"optimized": "otimizado",
		"optimization": "otimização",
		"flag": "flag",
		"flags": "flags",
		"option": "opção",
		"options": "opções",
		"argument list": "lista de argumentos",

		"syntax": "sintaxe",
		"semantic": "semântica",
		"semantics": "semântica",
		"token": "token",
		"tokens": "tokens",
		"parser": "parser",
		"parse": "analisar",
		"parsed": "analisado",
		"grammar": "gramática",
		"rule": "regra",
		"rules": "regras",

		"loop": "laço",
		"loops": "laços",
		"for": "for",
		"while": "while",
		"if": "if",
		"else": "else",
		"elif": "elif",
		"match": "match",
		"case": "caso",
		"switch": "switch",
		"break": "break",
		"continue": "continue",
		"return": "return",
		"yield": "yield",
		"await": "await",
		"async": "assíncrono",
		"sync": "síncrono",

		"true": "verdadeiro",
		"false": "falso",
		"none": "nenhum",
		"null": "nulo",
		"undefined": "indefinido",
		"default value": "valor padrão",

		"overflow": "estouro",
		"underflow": "subfluxo",
		"divide": "dividir",
		"division": "divisão",
		"zero": "zero",
		"nan": "nan",
		"infinity": "infinito",

		"path separator": "separador de caminho",
		"newline": "quebra de linha",
		"whitespace": "espaço em branco",
		"tab": "tabulação",
		"space": "espaço",
		"spaces": "espaços",
		"indent": "indentar",
		"indentation": "indentação",
		"unindent": "desindentar",

		"config": "configuração",
		"configs": "configurações",
		"configuration": "configuração",
		"settings": "configurações",
		"option file": "arquivo de opções",
		"config file": "arquivo de configuração",
		"env": "ambiente",
		".env file": "arquivo .env",

		"log": "log",
		"logs": "logs",
		"logging": "registro de logs",
		"level": "nível",
		"levels": "níveis",
		"verbose": "verboso",
		"verbosity": "verbosidade",
		"trace level": "nível de rastreamento",
		"debug level": "nível de depuração",
		"error level": "nível de erro",

		"queue": "fila",
		"queues": "filas",
		"stack": "pilha",
		"heap": "heap",
		"buffer": "buffer",
		"buffers": "buffers",
		"cache": "cache",
		"cached": "em cache",
		"hit": "acerto",
		"miss": "falha",

		"thread-safe": "seguro para threads",
		"unsafe": "inseguro",
		"race": "condição de corrida",
		"deadlock": "deadlock",
		"lock": "bloqueio",
		"locks": "bloqueios",
		"mutex": "mutex",
		"semaphore": "semáforo",

		"timeout value": "valor de tempo limite",
		"retry count": "número de tentativas",
		"interval": "intervalo",
		"delay": "atraso",
		"schedule": "agendar",
		"scheduled": "agendado",
		"job": "tarefa",
		"jobs": "tarefas",
		"task": "tarefa",
		"tasks": "tarefas",
		"worker": "worker",
		"workers": "workers",

		"host key": "chave do host",
		"public key": "chave pública",
		"private key": "chave privada",
		"fingerprint": "impressão digital",
		"cipher": "cifra",
		"algorithm": "algoritmo",
		"algorithms": "algoritmos",
		"hash": "hash",
		"hashed": "com hash",
		"salt": "sal",
		"iv": "vetor de inicialização",

		"session id": "id de sessão",
		"request id": "id de requisição",
		"transaction id": "id de transação",
		"trace id": "id de rastreamento",

		"http": "http",
		"https": "https",
		"method": "método",
		"methods": "métodos",
		"get": "get",
		"post": "post",
		"put": "put",
		"delete": "delete",
		"patch": "patch",
		"head": "head",
		"options method": "método options",
		"status code": "código de status",
		"headers": "cabeçalhos",
		"header": "cabeçalho",
		"body": "corpo",
		"payload": "payload",
		"cookie": "cookie",
		"cookies": "cookies",
		"session cookie": "cookie de sessão",

		"json": "json",
		"xml": "xml",
		"yaml": "yaml",
		"toml": "toml",
		"csv": "csv",
		"binary": "binário",
		"text": "texto",
		"format": "formato",
		"compressed": "comprimido",
		"uncompressed": "descomprimido",
		"archive": "arquivo compactado",
		"tar": "tar",
		"zip": "zip",
		"gzip": "gzip",
		"bzip2": "bzip2",

		"cli": "linha de comando",
		"shell": "shell",
		"terminal": "terminal",
		"console": "console",
		"prompt": "prompt",
		"command": "comando",
		"commands": "comandos",
		"script file": "arquivo de script",
		"stdout": "stdout",
		"stderr": "stderr",
		"stdin": "stdin",
		"pipe": "pipe",
		"piped": "encadeado",
		"exit code": "código de saída",
		"exit status": "status de saída",

		"linux": "linux",
		"windows": "windows",
		"macos": "macos",
		"unix": "unix",
		"distribution": "distribuição",
		"kernel version": "versão do kernel",
		"shell script": "script de shell",
		"batch file": "arquivo em lote",
		"service manager": "gerenciador de serviços",

		"host name": "nome do host",
		"hostname": "hostname",
		"fqdn": "nome de domínio completo",
		"subdomain": "subdomínio",
		"top-level domain": "domínio de topo",

		"cluster": "cluster",
		"node": "nó",
		"nodes": "nós",
		"master": "mestre",
		"worker node": "nó de trabalho",
		"leader": "líder",
		"follower": "seguidor",

		"queue length": "tamanho da fila",
		"load": "carga",
		"uptime": "tempo de atividade",
		"downtime": "tempo de inatividade",
		"health check": "verificação de saúde",
		"healthy": "saudável",
		"unhealthy": "não saudável",

		"role": "papel",
		"roles": "papéis",
		"policy": "política",
		"policies": "políticas",
		"scope": "escopo",
		"scopes": "escopos",

		"snapshot": "snapshot",
		"backup": "backup",
		"restore": "restaurar",
		"restored": "restaurado",

		"metrics": "métricas",
		"monitoring": "monitoramento",
		"alert": "alerta",
		"alerts": "alertas",
		"threshold": "limite",
		"thresholds": "limites",

		"schema migration": "migração de esquema",
		"migration": "migração",
		"migrations": "migrações",
		"seed": "seed",
		"seeding": "semeando",

		"orphan": "órfão",
		"stale": "obsoleto",
		"deprecated": "obsoleto",
		"legacy": "legado",
		"modern": "moderno",

		"hook": "gancho",
		"hooks": "ganchos",
		"callback": "callback",
		"callbacks": "callbacks",
		"handler": "handler",
		"handlers": "handlers",
		"middleware": "middleware",

		"queue worker": "worker de fila",
		"job queue": "fila de tarefas",
		"background": "plano de fundo",
		"foreground": "primeiro plano",

		"interactive": "interativo",
		"non-interactive": "não interativo",
		"batch": "lote",

		"start": "iniciar",
		"stop": "parar",
		"restart": "reiniciar",
		"reload": "recarregar",
		"restarted": "reiniciado",
		"reloaded": "recarregado",

		"alias": "apelido",
		"shortcut": "atalho",

		"orphaned process": "processo órfão",
		"zombie process": "processo zumbi",

		"priority": "prioridade",
		"priorities": "prioridades",

		"min": "mínimo",
		"max": "máximo",
		"average": "média",
		"median": "mediana",

		"sample": "amostra",
		"samples": "amostras",

		"pool": "pool",
		"pools": "pools",

		"retry policy": "política de novas tentativas",
	"pip": "pip",
	"npm": "npm",
	"package manager": "gerenciador de pacotes",
	"install": "instalar",
	"installed": "instalado",
	"uninstall": "desinstalar",
	"uninstalled": "desinstalado",
	"update": "atualizar",
	"upgrade": "atualizar",
	"downgrade": "reverter versão",
		"allocator": "alocador",
		"allocation": "alocação",
		"allocated": "alocado",
		"deallocated": "desalocado",
		"leak": "vazamento",
		"memory leak": "vazamento de memória",
		"profile": "perfil",
		"profiling": "perfilamento",
		"sampler": "amostrador",

		"event": "evento",
		"events": "eventos",
		"listener": "ouvinte",
		"listeners": "ouvintes",
		"subscriber": "assinante",
		"publish": "publicar",
		"publisher": "publicador",
		"subscribe": "assinar",
		"unsubscribe": "cancelar assinatura",
		"queue name": "nome da fila",
		"topic": "tópico",
		"topics": "tópicos",

		"retry delay": "atraso entre tentativas",
		"backoff": "retrocesso",
		"exponential backoff": "retrocesso exponencial",

		"ipv4": "ipv4",
		"ipv6": "ipv6",
		"subnet": "sub-rede",
		"subnet mask": "máscara de sub-rede",
		"cidr": "cidr",
		"mac address": "endereço mac",

		"stdin redirection": "redirecionamento de stdin",
		"stdout redirection": "redirecionamento de stdout",
		"stderr redirection": "redirecionamento de stderr",
		"here document": "here document",

		"orphaned resource": "recurso órfão",
		"cleanup": "limpeza",
		"garbage collector": "coletor de lixo",
		"finalizer": "finalizador",

		"namespace": "namespace",
		"namespaces": "namespaces",
		"scope leak": "vazamento de escopo",

		"bootstrap": "bootstrap",
		"bootstrapper": "inicializador",
		"initializer": "inicializador",

		"lifecycle": "ciclo de vida",
		"startup": "inicialização",
		"shutdown": "desligamento",

		"security": "segurança",
		"vulnerability": "vulnerabilidade",
		"vulnerabilities": "vulnerabilidades",
		"exploit": "exploit",
		"attack": "ataque",
		"attacker": "atacante",
		"defender": "defensor",
		"authorization": "autorização",
		"authentication": "autenticação",
		"confidentiality": "confidencialidade",
		"integrity": "integridade",
		"availability": "disponibilidade",
		"audit": "auditoria",
		"auditing": "auditoria",
		"compliance": "conformidade",

		"role-based access control": "controle de acesso baseado em papéis",
		"access control list": "lista de controle de acesso",

		"sql": "sql",
		"nosql": "nosql",
		"query plan": "plano de consulta",
		"optimizer": "otimizador",
		"index scan": "varredura de índice",
		"table scan": "varredura de tabela",
		"lock wait": "espera de bloqueio",

		"hot standby": "standby quente",
		"replica": "réplica",
		"replication": "replicação",
		"primary": "primário",
		"secondary": "secundário",

		"leader election": "eleição de líder",
		"consensus": "consenso",
		"quorum": "quórum",

		"blob": "blob",
		"object storage": "armazenamento de objetos",
		"filesystem": "sistema de arquivos",

		"pagination": "paginação",
		"offset pagination": "paginação por deslocamento",
		"cursor pagination": "paginação por cursor",

		"throttling": "restrição de taxa",
		"rate limit": "limite de taxa",

		"cache key": "chave de cache",
		"cache entry": "entrada de cache",
		"cache size": "tamanho do cache",

		"api": "api",
		"endpoint": "endpoint",
		"endpoints": "endpoints",
		"versioning": "versionamento",

		"schema validation": "validação de esquema",
		"validator": "validador",
		"validation": "validação",

		"serializer": "serializador",
		"deserializer": "desserializador",

		"middleware stack": "pilha de middleware",

		"job id": "id da tarefa",
		"task id": "id da tarefa",

		"cron": "cron",
		"cron job": "tarefa cron",
		"schedule expression": "expressão de agendamento",

		"kernel panic": "pânico do kernel",
		"panic": "pânico",

		"cgroup": "cgroup",
		"namespace isolation": "isolamento de namespace",

		"dockerfile": "dockerfile",
		"entrypoint": "entrypoint",
		"healthcheck": "verificação de saúde",
		"bind mount": "montagem vinculada",
		"overlay": "overlay",

		"image id": "id da imagem",
		"container id": "id do contêiner",
		"layer": "camada",
		"layers": "camadas",

		"bridge network": "rede bridge",
		"overlay network": "rede overlay",

		"git hook": "gancho do git",
		"pre-commit": "pre-commit",
		"pre-push": "pre-push",
		"post-merge": "post-merge",

		"remote url": "url remota",
		"upstream": "upstream",
		"origin url": "url do origin",

		"stash pop": "stash pop",
		"stash apply": "stash apply",

		"reflog": "reflog",
		"HEAD": "HEAD",

		"tag name": "nome da tag",
		"branch name": "nome da branch",

		"fast-forward": "fast-forward",

		"bare repository": "repositório nu",

		"venv path": "caminho do venv",
		"site-packages": "site-packages",

		"requirements file": "arquivo de requisitos",

		"pip cache": "cache do pip",
		"wheel": "wheel",
		"source distribution": "distribuição de código-fonte",

		"lock file": "arquivo de bloqueio",
		"package.json": "package.json",
		"package-lock.json": "package-lock.json",
		"node_modules": "node_modules",

		"linter": "linter",
		"formatter": "formatador",
		"static analysis": "análise estática",

		"type checker": "verificador de tipos",
		"mypy": "mypy",
		"flake8": "flake8",
		"pylint": "pylint",
		"black": "black",

		"coverage": "cobertura",
		"unit test": "teste unitário",
		"integration test": "teste de integração",
		"test suite": "suíte de testes",
		"test runner": "executor de testes",

		"assertion": "assertiva",
		"assert": "assert",

		"fixture": "fixture",

		"event loop": "loop de eventos",
		"future": "future",
		"promise": "promise",

		"main thread": "thread principal",
		"worker thread": "thread de trabalho",

		"critical section": "seção crítica",

		"hot reload": "recarga a quente",
		"hot restart": "reinício a quente",

		"websocket": "websocket",
		"handshake timeout": "tempo limite do handshake",
		"frame size": "tamanho do quadro",

		"csrf": "csrf",
		"xss": "xss",
		"sqli": "injeção sql",
		"open redirect": "redirecionamento aberto",

		"csrf token": "token csrf",

		"ip whitelist": "lista branca de ip",
		"ip blacklist": "lista negra de ip",
		"allowlist": "lista de permitidos",
		"denylist": "lista de negados",

		"session store": "armazenamento de sessão",

		"load balancer": "balanceador de carga",
		"backend": "backend",
		"frontend": "frontend",
		"upstream server": "servidor upstream",
		"health probe": "sonda de saúde",

		"request queue": "fila de requisições",

		"circuit breaker": "disjuntor",
		"fallback": "alternativa",
		"bulkhead": "compartimento",

		"trace span": "span de rastreamento",
		"span": "span",

		"observability": "observabilidade",
		"telemetry": "telemetria",

		"metric": "métrica",
		"counter": "contador",
		"gauge": "medidor",
		"histogram": "histograma",

		"dashboard": "painel",
		"panel": "painel",

		"namespace conflict": "conflito de namespace",

		"override": "sobrescrever",
		"overridden value": "valor sobrescrito",

		"feature flag": "flag de funcionalidade",

		"rollback plan": "plano de rollback",
		"deployment": "implantação",
		"deploy": "implantar",
		"release": "release",
		"canary": "canário",
		"blue-green": "blue-green",

		"maintenance": "manutenção",
		"maintenance window": "janela de manutenção",

		"hotfix": "hotfix",
		"bugfix": "correção de bug",

		"changelog": "changelog",

		"semantic versioning": "versionamento semântico",
		"major": "maior",
		"minor": "menor",
		"patch level": "nível de patch",

		"artifact": "artefato",
		"artifact repository": "repositório de artefatos",

		"ci": "ci",
		"cd": "cd",
		"pipeline": "pipeline",
		"stage": "estágio",
		"job step": "etapa de tarefa",

		"runner": "runner",
		"agent": "agente",

		"workspace": "workspace",
		"working directory": "diretório de trabalho",

		"checkout": "checkout",

		"environment variable": "variável de ambiente",
		"secret": "segredo",
		"secrets": "segredos",

		"mask": "mascarar",
		"masked": "mascarado",

		"retry strategy": "estratégia de novas tentativas",

		"quota": "cota",
		"hard limit": "limite rígido",
		"soft limit": "limite flexível",

		"session timeout": "tempo limite de sessão",

		"keepalive": "keepalive",

		"ping": "ping",
		"pong": "pong",

		"round-trip time": "tempo de ida e volta",

		"dns cache": "cache de dns",
		"resolver": "resolvedor",

		"trust store": "repositório de confiança",
		"key store": "repositório de chaves",

		"tls version": "versão de tls",
		"cipher suite": "conjunto de cifras",

		"handshake failure": "falha no handshake",

		"loopback": "loopback",

		"gateway timeout": "tempo limite do gateway",

		"service discovery": "descoberta de serviços",

		"http proxy": "proxy http",
		"https proxy": "proxy https",

		"upstream timeout": "tempo limite do upstream",

		"body size": "tamanho do corpo",
		"header size": "tamanho do cabeçalho",

		"idle connection": "conexão ociosa",

		"prefetch": "pré-busca",
		"preload": "pré-carregar",

		"warmup": "aquecimento",

		"rolling update": "atualização gradual",

		"replica count": "número de réplicas",

		"pod": "pod",
		"namespace (k8s)": "namespace (k8s)",
		"cluster ip": "ip de cluster",
		"node port": "porta de nó",
		"ingress": "ingress",
		"egress": "egress",

		"service account": "conta de serviço",

		"config map": "config map",
		"secret mount": "montagem de segredo",

		"readiness probe": "sonda de prontidão",
		"liveness probe": "sonda de vida",

		"init container": "contêiner de inicialização",

		"sidecar": "sidecar",	"dependency": "dependência",
	"dependencies": "dependências",
	"version": "versão",
	"versions": "versões",
	"lockfile": "arquivo de bloqueio",
	"registry": "registro",
	"global": "global",
	"local": "local",
	"virtualenv": "ambiente virtual",
	"venv": "venv",
		 "ERROR: unknown command": "ERRO: comando desconhecido",
    "maybe you meant": "talvez você quis dizer",
    "Package": "Pacote",
    "Version": "Versão",
    "Successfully installed": "Instalado com sucesso",
    "Requirement already satisfied": "Dependência já satisfeita",
    "Installing": "Instalando",
    "Uninstalling": "Desinstalando",
    "Updating": "Atualizando",
    "Up-to-date": "Atualizado",
    "Dependency": "Dependência",
    "Module": "Módulo",
    "Command": "Comando",
    "Not recognized": "Não reconhecido",
    "File": "Arquivo",
    "Directory": "Diretório",
    "Permission denied": "Permissão negada",
    "Access denied": "Acesso negado",
    "The term": "O termo",
    "is not recognized": "não é reconhecido",
    "Cannot find path": "Não foi possível encontrar o caminho",
    "Traceback": "Rastreamento de erro",
    "Exception": "Exceção",
    "SyntaxError": "Erro de sintaxe",
    "IndentationError": "Erro de indentação",
    "NameError": "Erro de nome",
    "ImportError": "Erro de importação",
    "ModuleNotFoundError": "Módulo não encontrado",
		"Operation not permitted": "Operação não permitida",
		"Connection refused": "Conexão recusada",
		"Command not found": "Comando não encontrado",
		"No such file or directory": "Arquivo ou diretório inexistente",
		"Operation timed out": "Operação expirou",
		"Invalid argument": "Argumento inválido",
		"Segmentation fault": "Falha de segmentação",
		"Broken pipe": "Pipe quebrado",
		"Read-only file system": "Sistema de arquivos somente leitura",
		"Out of memory": "Memória insuficiente",
		"Device or resource busy": "Dispositivo ou recurso ocupado",
		"Network is unreachable": "Rede inacessível",
		"Connection timed out": "Conexão expirada",
		"Host unreachable": "Host inacessível",
		"Permission error": "Erro de permissão",
		"Unknown error": "Erro desconhecido",
		"Invalid option": "Opção inválida",
		"Invalid command": "Comando inválido",
		"Invalid input": "Entrada inválida",
		"Invalid syntax": "Sintaxe inválida",
		"Invalid path": "Caminho inválido",
		"Path not found": "Caminho não encontrado",
		"Disk full": "Disco cheio",
		"No space left on device": "Sem espaço disponível no dispositivo",
		"Device not ready": "Dispositivo não está pronto",
		"Access is denied": "Acesso negado",
		"Operation aborted": "Operação abortada",
		"Operation failed": "Operação falhou",
		"Operation successful": "Operação bem-sucedida",
		"reset": "redefinida",
		"error": "erro",
		"not": "não",
		"temporarily": "temporariamente",
		"internal": "interno",
		"bad": "inválida",
		"timed": "expirou",
		"already": "já",
		"use": "em uso",
		"in": "em",
		"progress": "andamento",
		"broken": "quebrada",
		"exists": "existe",
		"busy": "ocupado",
		"only": "somente",
		"cannot": "não foi possível",
		"descriptor": "descritor",
		"end": "fim",
		"corrupted": "corrompido",
		"too": "muito",
		"large": "grande",
		"long": "longo",
		"operation": "operação",
		"feature": "funcionalidade",
		"implemented": "implementada",
		"responding": "respondendo",
		"unexpected": "inesperada",
		"checksum": "checksum",
		"data": "dados",
		"parsing": "parsing",
		"decode": "decodificar",
		"encode": "codificar",
		"compilation": "compilação",
		"logical": "lógico",
		"zerodivision": "divisão por zero",
		"warning": "aviso",
		"deprecation": "descontinuação",
		"keyboardinterrupt": "interrupção pelo teclado",
		"systemexit": "saída do sistema",
		"oserror": "sistema operacional",
		"ioerror": "entrada/saída",
		"exited": "finalizado",
		"terminated": "encerrado",
		"killed": "morto",
		"illegal": "ilegal",
		"instruction": "instrução",
		"abort": "aborto",
		"many": "excesso",
		"socket": "socket",
		"unreachable": "inacessível",
		"code": "código",
		"unhandled": "não tratado",
		"exception": "exceção",
		"initialization": "inicialização",
		"state": "estado",
		"concurrency": "concorrência",
		"duplicate": "duplicada",
		"privileges": "privilégios",
		"rate": "limite de requisições",
		"bind": "vincular",
		"listen": "escutar",
		"accept": "aceitar",
		"send": "enviar",
		"receive": "receber",
		"down": "inativo",
		"executed": "executado",
		"nothing": "nada",
		"rejected": "rejeitada",
		"required": "necessária",
		"i/o": "E/S",
		"mount": "montar",
		"violation": "violação",
		"segmentation": "segmentação",
		"bus": "barramento",
		"garbage": "lixo",
		"collection": "coleta",
		"low": "pouca",
		"unicode": "Unicode",
		"character": "caractere",
		"time": "tempo",
		"synchronization": "sincronização",
		"clock": "relógio",
		"skew": "diferença",
		"timestamp": "carimbo",
		"plugin": "plugin",
		"circular": "circular",
		"license": "licença",
		"encryption": "criptografia",
		"decryption": "descriptografia",
		"revoked": "revogado",
		"secure": "segura",
		"sandbox": "sandbox",
		"media": "mídia",
		"codec": "codec",
		"recognized": "reconhecido",
		"redirection": "redirecionamento",
		"temporary": "temporária",
		"permanent": "permanente",
		"lookup": "resolução",
		"resolve": "resolver",
		"forcibly": "à força",
		"negotiation": "negociação",
		"insecure": "insegura",
		"interface": "interface",
		"exhausted": "esgotado",
		"elevation": "elevação",
		"drive": "unidade",
		"sharing": "compartilhamento",
		"specified": "especificado",
		"ready": "pronto",
		"fatal": "fatal",
		"critical": "crítico",
		"core": "core",
		"dumped": "gerado",
		"refs": "refs",
		"working": "árvore de trabalho",
		"clean": "limpa",
		"detached": "destacado",
		"manifest": "manifesto",
		"entry": "entrada",
		"foreign": "estrangeira",
		"unique": "unico",
		"check": "verificação",
		"satisfies": "satisfaça",
		"errno": "errno",
		"enoent": "inexistente",
		"peer": "par",
		"elifecycle": "ELIFECYCLE",
		"eaccess": "EACCES",
		"eaddrinuse": "EADDRINUSE",
		"enotfound": "ENOTFOUND",
		"coroutine": "coroutine",
		"recursion": "recursão",
		"depth": "profundidade",
		"referenced": "referenciada",
		"assignment": "atribuição",
		"import": "importar",
		"indented": "indentado",
		"block": "bloco",
		"eol": "fim de linha",
		"literal": "literal",
		"unterminated": "não terminada",
		"changed": "mudou",
		"iteration": "iteração",
		"nonetype": "NoneType",
		"subscriptable": "indexável",
		"operand": "operando",
		"serializable": "serializável"
	}

